let masters = [
  {
    firstName: 'Jesper Eriksen',
    flag: '../../assets/flags/denmark.png',
    sprite1: '../../assets/sprites/yanmega.png',
    sprite2: '../../assets/sprites/vespiquen.png',
    list: '../../assets/list-icon.png',
    type: 'grass',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Yanmega BREAK", "set": "STS", "number": "8" },
        { "count": 4, "name": "Yanmega", "set": "STS", "number": "7" },
        { "count": 4, "name": "Yanma", "set": "PHF", "number": "3" },
        { "count": 4, "name": "Vespiquen", "set": "AOR", "number": "10" },
        { "count": 4, "name": "Combee", "set": "AOR", "number": "9" },
        { "count": 1, "name": "Ariados", "set": "AOR", "number": "6" },
        { "count": 1, "name": "Spinarak", "set": "AOR", "number": "5" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Judge", "set": "BKT", "number": "143" },
        { "count": 2, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 2, "name": "Level Ball", "set": "AOR", "number": "76" },
        { "count": 2, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 1, "name": "Revitalizer", "set": "GEN", "number": "70" },
        { "count": 1, "name": "Special Charge", "set": "STS", "number": "105" },
        { "count": 4, "name": "Bursting Balloon", "set": "BKP", "number": "97" },
        { "count": 4, "name": "Forest of Giant Plants", "set": "AOR", "number": "74" },
      ], "energy": [
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Connor Pedersen',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PHF", "number": "31" },
        { "count": 1, "name": "Lugia-EX", "set": "AOR", "number": "68" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "FCO", "number": "105" },
        { "count": 2, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Delinquent", "set": "BKP", "number": "98" },
        { "count": 1, "name": "Skyla", "set": "BKT", "number": "148" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Super Rod", "set": "BKT", "number": "149" },
        { "count": 3, "name": "Fighting Fury Belt", "set": "BKP", "number": "99" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
        { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
      ], "energy": [
        { "count": 5, "name": "Water Energy", "set": "XY", "number": "134" },
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Raphael Souto',
    flag: '../../assets/flags/brazil.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/trevenant.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Trevenant BREAK", "set": "BKP", "number": "66" },
        { "count": 4, "name": "Trevenant", "set": "XY", "number": "55" },
        { "count": 4, "name": "Phantump", "set": "BKP", "number": "64" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "Steven", "set": "ROS", "number": "90" },
        { "count": 3, "name": "N", "set": "FCO", "number": "105" },
        { "count": 2, "name": "Team Flare Grunt", "set": "XY", "number": "129" },
        { "count": 1, "name": "Wally", "set": "ROS", "number": "94" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Crushing Hammer", "set": "KSS", "number": "34" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 2, "name": "Super Rod", "set": "BKT", "number": "149" },
        { "count": 2, "name": "Level Ball", "set": "AOR", "number": "76" },
        { "count": 1, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 8, "name": "Psychic Energy", "set": "XY", "number": "136" },
      ]
    },
  },
  {
    firstName: 'Calvin Connor',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/vespiquen.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Vespiquen", "set": "AOR", "number": "10" },
        { "count": 3, "name": "Combee", "set": "AOR", "number": "9" },
        { "count": 4, "name": "Unown", "set": "AOR", "number": "30" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Pokémon Ranger", "set": "STS", "number": "104" },
        { "count": 1, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Hex Maniac", "set": "AOR", "number": "75" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Puzzle of Time", "set": "BKP", "number": "109" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 1, "name": "Town Map", "set": "BKT", "number": "150" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Fighting Fury Belt", "set": "BKP", "number": "99" },
        { "count": 2, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Attar Ricco',
    flag: '../../assets/flags/indonesia.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 1, "name": "Galvantula", "set": "STS", "number": "42" },
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 1, "name": "Mew", "set": "FCO", "number": "29" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Hex Maniac", "set": "AOR", "number": "75" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Pokémon Ranger", "set": "STS", "number": "104" },
        { "count": 1, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Puzzle of Time", "set": "BKP", "number": "109" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Target Whistle Team Flare Gear", "set": "PHF", "number": "106" },
        { "count": 1, "name": "Town Map", "set": "BKT", "number": "150" },
        { "count": 1, "name": "Fighting Fury Belt", "set": "BKP", "number": "99" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 1, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Spencer Perez-Dormitzer',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/manectric-mega.png',
    sprite2: '../../assets/sprites/garbodor.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
        { "count": 4, "name": "Manectric-EX", "set": "PHF", "number": "23" },
        { "count": 2, "name": "Garbodor", "set": "BKP", "number": "57" },
        { "count": 2, "name": "Trubbish", "set": "BKP", "number": "56" },
        { "count": 1, "name": "Raikou", "set": "BKT", "number": "55" },
        { "count": 1, "name": "Jolteon-EX", "set": "GEN", "number": "28" },
        { "count": 1, "name": "Hoopa-EX", "set": "AOR", "number": "36" },
        { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 2, "name": "Max Elixir", "set": "BKP", "number": "102" },
        { "count": 1, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 1, "name": "Max Potion", "set": "BKP", "number": "103" },
        { "count": 1, "name": "Super Rod", "set": "BKT", "number": "149" },
        { "count": 3, "name": "Manectric Spirit Link", "set": "PHF", "number": "100" },
        { "count": 2, "name": "Float Stone", "set": "BKT", "number": "137" },
        { "count": 3, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 9, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 3, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Tanner Hurley',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/greninja.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Greninja BREAK", "set": "BKP", "number": "41" },
        { "count": 3, "name": "Greninja", "set": "BKP", "number": "40" },
        { "count": 1, "name": "Greninja", "set": "XY", "number": "41" },
        { "count": 4, "name": "Frogadier", "set": "BKP", "number": "39" },
        { "count": 3, "name": "Froakie", "set": "BKP", "number": "38" },
        { "count": 4, "name": "Talonflame", "set": "STS", "number": "96" },
        { "count": 1, "name": "Jirachi", "set": "PR-XY", "number": "67" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Ace Trainer", "set": "AOR", "number": "69" },
        { "count": 1, "name": "Fisherman", "set": "BKT", "number": "136" },
        { "count": 1, "name": "Pokémon Ranger", "set": "STS", "number": "104" },
        { "count": 4, "name": "Dive Ball", "set": "PRC", "number": "125" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 2, "name": "Level Ball", "set": "AOR", "number": "76" },
        { "count": 2, "name": "Super Rod", "set": "BKT", "number": "149" },
        { "count": 1, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Town Map", "set": "BKT", "number": "150" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 1, "name": "Energy Retrieval", "set": "PRC", "number": "126" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 7, "name": "Water Energy", "set": "XY", "number": "134" },
        { "count": 1, "name": "Unknown", "set": "FR", "number": "75632" },
      ]
    },
    deck: [
      {
        cardImg: '../../assets/question-mark/2014-2016',
        numImg: '../../assets/01.png'
      },
    ]
  },
  {
    firstName: 'Kim Hyeok',
    flag: '../../assets/flags/korea.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 2, "name": "Mew", "set": "FCO", "number": "29" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Hex Maniac", "set": "AOR", "number": "75" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Pokémon Ranger", "set": "STS", "number": "104" },
        { "count": 1, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Puzzle of Time", "set": "BKP", "number": "109" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Special Charge", "set": "STS", "number": "105" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 2, "name": "Fighting Fury Belt", "set": "BKP", "number": "99" },
        { "count": 1, "name": "Float Stone", "set": "BKT", "number": "137" },
        { "count": 3, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  },
  {
    firstName: 'Jon Eng',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/greninja.png',
    list: '../../assets/sprites/blank.png',
    type: '',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  },
  {
    firstName: 'Alex Bobenrieth',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/yveltal.png',
    sprite2: '../../assets/sprites/zoroark.png',
    list: '../../assets/list-icon.png',
    type: 'dark',
    event: '2016 World Championships - Seniors',
    decklist: {
      "pokemon": [
        { "count": 2, "name": "Yveltal", "set": "BKT", "number": "94" },
        { "count": 2, "name": "Yveltal", "set": "STS", "number": "65" },
        { "count": 1, "name": "Yveltal-EX", "set": "PR-XY", "number": "150" },
        { "count": 2, "name": "Zoroark", "set": "BKT", "number": "91" },
        { "count": 1, "name": "Zorua", "set": "BKT", "number": "89" },
        { "count": 1, "name": "Zorua", "set": "BKT", "number": "90" },
        { "count": 2, "name": "Gallade", "set": "BKT", "number": "84" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi", "set": "PR-XY", "number": "67" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "N", "set": "FCO", "number": "105" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Maxie's Hidden Ball Trick", "set": "PRC", "number": "133" },
        { "count": 1, "name": "Delinquent", "set": "BKP", "number": "98" },
        { "count": 1, "name": "Hex Maniac", "set": "AOR", "number": "75" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Puzzle of Time", "set": "BKP", "number": "109" },
        { "count": 3, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 2, "name": "Bursting Balloon", "set": "BKP", "number": "97" },
        { "count": 2, "name": "Float Stone", "set": "BKT", "number": "137" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Parallel City", "set": "BKT", "number": "145" },
        { "count": 1, "name": "Reverse Valley", "set": "BKP", "number": "110" },
      ], "energy": [
        { "count": 7, "name": "Darkness Energy", "set": "XY", "number": "138" },
        { "count": 4, "name": "Double Colorless Energy", "set": "FCO", "number": "114" },
      ]
    },
  }
]