let masters = [
  {
    firstName: 'Jacob Van Wagner',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/keldeo-resolute.png',
    sprite2: '../../assets/sprites/blastoise.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 2, "name": "Blastoise", "set": "BCR", "number": "31" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        { "count": 2, "name": "Exeggcute", "set": "PLF", "number": "4" },
        { "count": 1, "name": "Articuno", "set": "ROS", "number": "17" },
        { "count": 1, "name": "Wailord-EX", "set": "PRC", "number": "38" },
        { "count": 1, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
      ], "trainer": [
        { "count": 2, "name": "Archie's Ace in the Hole", "set": "PRC", "number": "124" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Superior Energy Retrieval", "set": "PLF", "number": "103" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 4, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 11, "name": "Water Energy", "set": "XY", "number": "134" },
      ]
    },
  },
  {
    firstName: 'Mees Brenninkmeijer',
    flag: '../../assets/flags/netherlands.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 3, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 4, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 2, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 4, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 3, "name": "Water Energy", "set": "XY", "number": "134" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Igor Costa',
    flag: '../../assets/flags/portugal.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 3, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
        { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 4, "name": "Water Energy", "set": "XY", "number": "134" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Merlin Quittek',
    flag: '../../assets/flags/germany.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 4, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 3, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
      ], "trainer": [
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 1, "name": "Hard Charm", "set": "XY", "number": "119" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Sean Foisy',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/trevenant.png',
    sprite2: '../../assets/sprites/gengar.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Gengar-EX", "set": "PHF", "number": "34" },
        { "count": 4, "name": "Trevenant", "set": "XY", "number": "55" },
        { "count": 4, "name": "Phantump", "set": "XY", "number": "54" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 3, "name": "Wally", "set": "ROS", "number": "94" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
        { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
      ], "energy": [
        { "count": 2, "name": "Psychic Energy", "set": "XY", "number": "136" },
        { "count": 4, "name": "Mystery Energy", "set": "PHF", "number": "112" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Martin Janouš',
    flag: '../../assets/flags/czech-republic.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 1, "name": "Town Map", "set": "BCR", "number": "136" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Simon Narode',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/donphan.png',
    list: '../../assets/list-icon.png',
    type: 'fighting',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Donphan", "set": "PLS", "number": "72" },
        { "count": 4, "name": "Phanpy", "set": "PLS", "number": "71" },
        { "count": 4, "name": "Hawlucha", "set": "FFI", "number": "63" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
        { "count": 1, "name": "Mr. Mime", "set": "PLF", "number": "47" },
      ], "trainer": [
        { "count": 4, "name": "Korrina", "set": "FFI", "number": "95" },
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Robo Substitute Team Flare Gear", "set": "PHF", "number": "102" },
        { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Repeat Ball", "set": "PRC", "number": "136" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Focus Sash", "set": "FFI", "number": "91" },
        { "count": 1, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 3, "name": "Fighting Stadium", "set": "FFI", "number": "90" },
        { "count": 1, "name": "Silent Lab", "set": "PRC", "number": "140" },
      ], "energy": [
        { "count": 4, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Strong Energy", "set": "FFI", "number": "104" }, ,
        { "count": 2, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Tito Santoso',
    flag: '../../assets/flags/indonesia.png',
    sprite1: '../../assets/sprites/aromatisse.png',
    sprite2: '../../assets/sprites/seismitoad.png',
    list: '../../assets/list-icon.png',
    type: 'fairy',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 2, "name": "Aromatisse", "set": "XY", "number": "93" },
        { "count": 2, "name": "Spritzee", "set": "FLF", "number": "67" },
        { "count": 1, "name": "Spritzee", "set": "XY", "number": "92" },
        { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 1, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
        { "count": 1, "name": "Charizard-EX", "set": "FLF", "number": "12" },
        { "count": 1, "name": "Malamar-EX", "set": "PHF", "number": "58" },
        { "count": 1, "name": "Cobalion-EX", "set": "PLS", "number": "93" },
        { "count": 1, "name": "Trevenant-EX", "set": "PRC", "number": "19" },
        { "count": 1, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
        { "count": 1, "name": "Manectric-EX", "set": "PHF", "number": "23" },
        { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Pokémon Fan Club", "set": "FLF", "number": "94" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 3, "name": "Max Potion", "set": "EPO", "number": "94" },
        { "count": 2, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 4, "name": "Fairy Garden", "set": "XY", "number": "117" },
      ], "energy": [
        { "count": 5, "name": "Fairy Energy", "set": "XY", "number": "140" },
        { "count": 4, "name": "Rainbow Energy", "set": "XY", "number": "131" },
        { "count": 3, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Andrew Mahone',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
        { "count": 1, "name": "Virizion-EX", "set": "PLB", "number": "9" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 1, "name": "Town Map", "set": "BCR", "number": "136" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Grass Energy", "set": "XY", "number": "132" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Jason Martinez',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/manectric.png',
    list: '../../assets/sprites/blank.png',
    type: '',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  },
  {
    firstName: 'Simone Zucchelli',
    flag: '../../assets/flags/italy.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/sprites/blank.png',
    type: '',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  },
  {
    firstName: 'Ross Cawthon',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/groudon-primal.png',
    sprite2: '../../assets/sprites/wobbuffet.png',
    list: '../../assets/list-icon.png',
    type: 'fighting',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Primal Groudon-EX", "set": "PRC", "number": "86" },
        { "count": 3, "name": "Groudon-EX", "set": "PRC", "number": "85" },
        { "count": 3, "name": "Wobbuffet", "set": "PHF", "number": "36" },
        { "count": 1, "name": "Landorus-EX", "set": "BCR", "number": "89" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
      ], "trainer": [
        { "count": 4, "name": "Korrina", "set": "FFI", "number": "95" },
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 2, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Robo Substitute Team Flare Gear", "set": "PHF", "number": "102" },
        { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 1, "name": "Mega Turbo", "set": "ROS", "number": "86" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 2, "name": "Hard Charm", "set": "XY", "number": "119" },
        { "count": 1, "name": "Focus Sash", "set": "FFI", "number": "91" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 3, "name": "Silent Lab", "set": "PRC", "number": "140" },
        { "count": 1, "name": "Fighting Stadium", "set": "FFI", "number": "90" },
      ], "energy": [
        { "count": 7, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Strong Energy", "set": "FFI", "number": "104" },
      ]
    },
  },
  {
    firstName: 'Daniel Altavilla',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/manectric-mega.png',
    sprite2: '../../assets/sprites/genesect.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
        { "count": 4, "name": "Manectric-EX", "set": "PHF", "number": "23" },
        { "count": 2, "name": "Genesect-EX", "set": "PLB", "number": "11" },
        { "count": 1, "name": "Deoxys-EX", "set": "PLF", "number": "53" },
        { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 1, "name": "Shadow Triad", "set": "PLF", "number": "102" },
        { "count": 1, "name": "G Booster", "set": "PLB", "number": "92" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 2, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 2, "name": "Max Potion", "set": "EPO", "number": "94" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 3, "name": "Manectric Spirit Link", "set": "PHF", "number": "100" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 5, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Grass Energy", "set": "XY", "number": "132" },
        { "count": 2, "name": "Plasma Energy", "set": "PLS", "number": "127" },
      ]
    },
  },
  {
    firstName: 'Dylan Dreyer',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Michikazu Tsuda',
    flag: '../../assets/flags/japan.png',
    sprite1: '../../assets/sprites/raichu.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Raichu", "set": "XY", "number": "43" },
        { "count": 4, "name": "Pikachu", "set": "XY", "number": "42" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 4, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        { "count": 1, "name": "Bronzong", "set": "PHF", "number": "61" },
        { "count": 1, "name": "Bronzor", "set": "PHF", "number": "60" },
        { "count": 1, "name": "Mr. Mime", "set": "PLF", "number": "47" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 2, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 2, "name": "Sacred Ash", "set": "FLF", "number": "96" },
        { "count": 1, "name": "Repeat Ball", "set": "PRC", "number": "136" },
        { "count": 3, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 4, "name": "Sky Field", "set": "ROS", "number": "89" },
      ], "energy": [
        { "count": 3, "name": "Metal Energy", "set": "XY", "number": "139" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Nicolas Galaz',
    flag: '../../assets/flags/chile.png',
    sprite1: '../../assets/sprites/landorus-therian.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/sprites/blank.png',
    type: '',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  },
  {
    firstName: 'Junichi Kakinoki',
    flag: '../../assets/flags/japan.png',
    sprite1: '../../assets/sprites/manectric-mega.png',
    sprite2: '../../assets/sprites/yanmega.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
        { "count": 4, "name": "Manectric-EX", "set": "PHF", "number": "23" },
        { "count": 3, "name": "Yanmega", "set": "PHF", "number": "4" },
        { "count": 3, "name": "Yanma", "set": "PHF", "number": "3" },
        { "count": 2, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 1, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
        { "count": 1, "name": "Iris", "set": "PLB", "number": "81" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 3, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Max Potion", "set": "EPO", "number": "94" },
        { "count": 3, "name": "Manectric Spirit Link", "set": "PHF", "number": "100" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "BKT", "number": "137" },
        { "count": 3, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 8, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Henry Ross-Clunis',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Adrian Velasco',
    flag: '../../assets/flags/philippines.png',
    sprite1: '../../assets/sprites/trevenant.png',
    sprite2: '../../assets/sprites/gengar.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 2, "name": "Gengar-EX", "set": "PHF", "number": "34" },
        { "count": 3, "name": "Trevenant", "set": "XY", "number": "55" },
        { "count": 4, "name": "Phantump", "set": "XY", "number": "54" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 3, "name": "Wally", "set": "ROS", "number": "94" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Team Flare Grunt", "set": "XY", "number": "129" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 3, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Crushing Hammer", "set": "KSS", "number": "34" },
        { "count": 2, "name": "Enhanced Hammer", "set": "PHF", "number": "94" },
        { "count": 2, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
        { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 2, "name": "Psychic Energy", "set": "XY", "number": "136" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" }, ,
        { "count": 2, "name": "Mystery Energy", "set": "PHF", "number": "112" },
      ]
    },
  },
  {
    firstName: 'Jimmy Pendarvis',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/joltik.png',
    sprite2: '../../assets/sprites/pumpkaboo.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Joltik", "set": "PHF", "number": "26" },
        { "count": 4, "name": "Pumpkaboo", "set": "PHF", "number": "44" },
        { "count": 4, "name": "Lampent", "set": "PHF", "number": "42" },
        { "count": 3, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Mew-EX", "set": "LTR", "number": "RC24" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
        { "count": 1, "name": "Revive", "set": "ROS", "number": "88" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Dimension Valley", "set": "PHF", "number": "93" },
      ], "energy": [
        { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Sam Chen',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/keldeo-resolute.png',
    sprite2: '../../assets/sprites/blastoise.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 2, "name": "Blastoise", "set": "BCR", "number": "31" },
        { "count": 2, "name": "Articuno", "set": "ROS", "number": "17" },
        { "count": 2, "name": "Exeggcute", "set": "PLF", "number": "4" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
      ], "trainer": [
        { "count": 2, "name": "Archie's Ace in the Hole", "set": "PRC", "number": "124" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Superior Energy Retrieval", "set": "PLF", "number": "103" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 4, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 11, "name": "Water Energy", "set": "XY", "number": "134" },
      ]
    },
  },
  {
    firstName: 'Aaron Tarbell',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/keldeo-resolute.png',
    sprite2: '../../assets/sprites/blastoise.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 2, "name": "Blastoise", "set": "BCR", "number": "31" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        { "count": 2, "name": "Exeggcute", "set": "PLF", "number": "4" },
        { "count": 1, "name": "Wailord-EX", "set": "PRC", "number": "38" },
        { "count": 1, "name": "Articuno", "set": "ROS", "number": "17" },
        { "count": 1, "name": "Kyurem", "set": "PLF", "number": "31" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
      ], "trainer": [
        { "count": 2, "name": "Archie's Ace in the Hole", "set": "PRC", "number": "124" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Battle Compressor Team Flare Gear", "set": "PHF", "number": "92" },
        { "count": 4, "name": "Superior Energy Retrieval", "set": "PLF", "number": "103" },
        { "count": 4, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 3, "name": "Acro Bike", "set": "PRC", "number": "122" },
        { "count": 1, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Rough Seas", "set": "PRC", "number": "137" },
      ], "energy": [
        { "count": 11, "name": "Water Energy", "set": "XY", "number": "134" },
      ]
    },
  },
  {
    firstName: 'Ciaran Farah',
    flag: '../../assets/flags/canada.png',
    sprite1: '../../assets/sprites/raichu.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Raichu", "set": "XY", "number": "43" },
        { "count": 4, "name": "Pikachu", "set": "XY", "number": "42" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 4, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Leafeon", "set": "PLF", "number": "11" },
        { "count": 2, "name": "Eevee", "set": "FFI", "number": "80" },
        { "count": 1, "name": "Exeggcute", "set": "PLF", "number": "4" },
      ], "trainer": [
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
        { "count": 1, "name": "Repeat Ball", "set": "PRC", "number": "136" },
        { "count": 2, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 4, "name": "Sky Field", "set": "ROS", "number": "89" },
      ], "energy": [
        { "count": 3, "name": "Grass Energy", "set": "XY", "number": "132" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Daniel Lynch',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/donphan.png',
    list: '../../assets/list-icon.png',
    type: 'fighting',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Donphan", "set": "PLS", "number": "72" },
        { "count": 4, "name": "Phanpy", "set": "PLS", "number": "71" },
        { "count": 4, "name": "Hawlucha", "set": "FFI", "number": "63" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
      ], "trainer": [
        { "count": 4, "name": "Korrina", "set": "FFI", "number": "95" },
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 3, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Robo Substitute Team Flare Gear", "set": "PHF", "number": "102" },
        { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Focus Sash", "set": "FFI", "number": "91" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 2, "name": "Fighting Stadium", "set": "FFI", "number": "90" },
        { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
      ], "energy": [
        { "count": 5, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Strong Energy", "set": "FFI", "number": "104" }, ,
        { "count": 2, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Kian Amini',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/manectric.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 2, "name": "Manectric-EX", "set": "PHF", "number": "23" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
        { "count": 1, "name": "Rock Guard", "set": "PLF", "number": "108" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 3, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
        { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 4, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Jason Klaczynski',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/garbodor.png',
    list: '../../assets/list-icon.png',
    type: 'water',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 2, "name": "Garbodor", "set": "LTR", "number": "68" },
        { "count": 2, "name": "Trubbish", "set": "PLS", "number": "63" },
        { "count": 1, "name": "Hippowdon", "set": "PRC", "number": "88" },
        { "count": 1, "name": "Hippopotas", "set": "PRC", "number": "87" },
      ], "trainer": [
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Shadow Triad", "set": "PLF", "number": "102" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "Team Flare Grunt", "set": "XY", "number": "129" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 3, "name": "Crushing Hammer", "set": "KSS", "number": "34" },
        { "count": 1, "name": "Enhanced Hammer", "set": "PHF", "number": "94" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
        { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 3, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Alexander Hill',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/trevenant.png',
    sprite2: '../../assets/sprites/gengar.png',
    list: '../../assets/list-icon.png',
    type: 'psychic',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Trevenant", "set": "XY", "number": "55" },
        { "count": 4, "name": "Phantump", "set": "XY", "number": "54" },
        { "count": 3, "name": "Gengar-EX", "set": "PHF", "number": "34" },
        { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 3, "name": "Wally", "set": "ROS", "number": "94" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Trainers' Mail", "set": "ROS", "number": "92" },
        { "count": 4, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
        { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
      ], "energy": [
        { "count": 2, "name": "Psychic Energy", "set": "XY", "number": "136" },
        { "count": 4, "name": "Mystery Energy", "set": "PHF", "number": "112" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Tobias Thesing',
    flag: '../../assets/flags/germany.png',
    sprite1: '../../assets/sprites/raichu.png',
    sprite2: '../../assets/sprites/crobat.png',
    list: '../../assets/list-icon.png',
    type: 'lightning',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Raichu", "set": "XY", "number": "43" },
        { "count": 4, "name": "Pikachu", "set": "XY", "number": "42" },
        { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
        { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
        { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
        { "count": 2, "name": "Hawlucha", "set": "FFI", "number": "63" },
        { "count": 4, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
      ], "trainer": [
        { "count": 3, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 2, "name": "Silver Bangle", "set": "PLB", "number": "88" },
        { "count": 4, "name": "Sky Field", "set": "ROS", "number": "89" },
      ], "energy": [
        { "count": 4, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Brit Pybas',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/aegislash.png',
    sprite2: '../../assets/sprites/bronzong.png',
    list: '../../assets/list-icon.png',
    type: 'metal',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Bronzong", "set": "PHF", "number": "61" },
        { "count": 4, "name": "Bronzor", "set": "PHF", "number": "60" },
        { "count": 2, "name": "Aegislash-EX", "set": "PHF", "number": "65" },
        { "count": 2, "name": "Heatran", "set": "PHF", "number": "63" },
        { "count": 1, "name": "Dialga-EX", "set": "PHF", "number": "62" },
        { "count": 1, "name": "Cobalion-EX", "set": "PLS", "number": "93" },
        { "count": 1, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 1, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
        { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Kecleon", "set": "PLF", "number": "94" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Steel Shelter", "set": "PHF", "number": "105" },
      ], "energy": [
        { "count": 8, "name": "Metal Energy", "set": "XY", "number": "139" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Patrik Räty',
    flag: '../../assets/flags/finland.png',
    sprite1: '../../assets/sprites/blank.png',
    sprite2: '../../assets/sprites/groudon-primal.png',
    list: '../../assets/sprites/blank.png',
     type: '',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  },
  {
    firstName: 'Dustin Zimmerman',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/aegislash.png',
    sprite2: '../../assets/sprites/bronzong.png',
    list: '../../assets/list-icon.png',
    type: 'metal',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Bronzong", "set": "PHF", "number": "61" },
        { "count": 4, "name": "Bronzor", "set": "PHF", "number": "60" },
        { "count": 2, "name": "Aegislash-EX", "set": "PHF", "number": "65" },
        { "count": 2, "name": "Heatran", "set": "PHF", "number": "63" },
        { "count": 1, "name": "Dialga-EX", "set": "PHF", "number": "62" },
        { "count": 1, "name": "Cobalion-EX", "set": "PLS", "number": "93" },
        { "count": 1, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
        { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        { "count": 1, "name": "Mewtwo-EX", "set": "LTR", "number": "54" },
        { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        { "count": 1, "name": "Kecleon", "set": "PLF", "number": "94" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
        { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Steel Shelter", "set": "PHF", "number": "105" },
      ], "energy": [
        {"count": 8, "name": "Metal Energy", "set": "XY", "number": "139"},
        {"count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130"},
      ]
    },
  },
  {
    firstName: 'Michael Diaz',
    flag: '../../assets/flags/usa.png',
    sprite1: '../../assets/sprites/seismitoad.png',
    sprite2: '../../assets/sprites/manectric.png',
    list: '../../assets/sprites/blank.png',
    type: '',
    event: '2015 World Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {
        cardImg: '../../assets/cards/2014-2016',
        numImg: '../../assets/04.png'
      },
    ]
  }
]
