let masters = [
    {
      firstName: 'Patrick Martinez',
      flag: '../../assets/flags/usa.png',
      sprite1: '../../assets/sprites/seismitoad.png',
      sprite2: '../../assets/sprites/manectric.png',
      list: '../../assets/list-icon.png',
      type: 'water',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
          { "count": 2, "name": "Manectric-EX", "set": "PHF", "number": "23" },
          { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
          { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
          { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
          { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        ], "trainer": [
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
          { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
          { "count": 1, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
          { "count": 1, "name": "Rock Guard", "set": "PLF", "number": "108" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
          { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 3, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
          { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
          { "count": 3, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
        ], "energy": [
          { "count": 4, "name": "Lightning Energy", "set": "XY", "number": "135" },
          { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Jeffrey Cheng',
      flag: '../../assets/flags/usa.png',
      sprite1: '../../assets/sprites/blank.png',
      sprite2: '../../assets/sprites/donphan.png',
      list: '../../assets/list-icon.png',
      type: 'fighting',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 4, "name": "Donphan", "set": "PLS", "number": "72" },
          { "count": 4, "name": "Phanpy", "set": "PLS", "number": "71" },
          { "count": 4, "name": "Hawlucha", "set": "FFI", "number": "63" },
          { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
          { "count": 1, "name": "Mr. Mime", "set": "PLF", "number": "47" },
        ], "trainer": [
          { "count": 4, "name": "Korrina", "set": "FFI", "number": "95" },
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Robo Substitute Team Flare Gear", "set": "PHF", "number": "102" },
          { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 3, "name": "Focus Sash", "set": "FFI", "number": "91" },
          { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Silver Bangle", "set": "PLB", "number": "88" },
          { "count": 2, "name": "Fighting Stadium", "set": "FFI", "number": "90" },
          { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
        ], "energy": [
          { "count": 5, "name": "Fighting Energy", "set": "XY", "number": "137" },
          { "count": 4, "name": "Strong Energy", "set": "FFI", "number": "104" }, ,
          { "count": 2, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Brent Tonisson',
      flag: '../../assets/flags/australia.png',
      sprite1: '../../assets/sprites/manectric-mega.png',
      sprite2: '../../assets/sprites/keldeo-resolute.png',
      list: '../../assets/list-icon.png',
      type: 'lightning',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 4, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
          { "count": 4, "name": "Manectric-EX", "set": "PHF", "number": "23" },
          { "count": 2, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
          { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
          { "count": 2, "name": "Zapdos", "set": "ROS", "number": "23" },
          { "count": 1, "name": "Mr. Mime", "set": "PLF", "number": "47" },
          { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
        ], "trainer": [
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 2, "name": "Enhanced Hammer", "set": "PHF", "number": "94" },
          { "count": 1, "name": "Escape Rope", "set": "PRC", "number": "127" },
          { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
          { "count": 4, "name": "Manectric Spirit Link", "set": "PHF", "number": "100" },
          { "count": 2, "name": "Float Stone", "set": "BKT", "number": "137" },
          { "count": 4, "name": "Rough Seas", "set": "PRC", "number": "137" },
        ], "energy": [
          { "count": 6, "name": "Lightning Energy", "set": "XY", "number": "135" },
          { "count": 4, "name": "Water Energy", "set": "XY", "number": "134" },
        ]
      },
    },
    {
      firstName: 'Colter Decker',
      flag: '../../assets/flags/usa.png',
      sprite1: '../../assets/sprites/blank.png',
      sprite2: '../../assets/sprites/donphan.png',
      list: '../../assets/list-icon.png',
      type: 'fighting',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 4, "name": "Donphan", "set": "PLS", "number": "72" },
          { "count": 4, "name": "Phanpy", "set": "PLS", "number": "71" },
          { "count": 4, "name": "Hawlucha", "set": "FFI", "number": "63" },
          { "count": 1, "name": "Bunnelby", "set": "PRC", "number": "121" },
        ], "trainer": [
          { "count": 4, "name": "Korrina", "set": "FFI", "number": "95" },
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 3, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Robo Substitute Team Flare Gear", "set": "PHF", "number": "102" },
          { "count": 3, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 3, "name": "Focus Sash", "set": "FFI", "number": "91" },
          { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Silver Bangle", "set": "PLB", "number": "88" },
          { "count": 2, "name": "Fighting Stadium", "set": "FFI", "number": "90" },
          { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
        ], "energy": [
          { "count": 5, "name": "Fighting Energy", "set": "XY", "number": "137" },
          { "count": 4, "name": "Strong Energy", "set": "FFI", "number": "104" }, ,
          { "count": 2, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Calvin Connor',
      flag: '../../assets/flags/usa.png',
      sprite1: '../../assets/sprites/klinklang.png',
      sprite2: '../../assets/sprites/bronzong.png',
      list: '../../assets/list-icon.png',
      type: 'metal',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 2, "name": "Klinklang", "set": "PLS", "number": "90" },
          { "count": 2, "name": "Klang", "set": "BLW", "number": "75" },
          { "count": 4, "name": "Klink", "set": "PLS", "number": "88" },
          { "count": 3, "name": "Bronzong", "set": "PHF", "number": "61" },
          { "count": 3, "name": "Bronzor", "set": "PHF", "number": "60" },
          { "count": 1, "name": "Heatran", "set": "PHF", "number": "63" },
          { "count": 2, "name": "Cobalion-EX", "set": "PLS", "number": "93" },
          { "count": 2, "name": "Aegislash-EX", "set": "PHF", "number": "65" },
          { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
          { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        ], "trainer": [
          { "count": 3, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
          { "count": 1, "name": "Teammates", "set": "PRC", "number": "141" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 1, "name": "Rare Candy", "set": "PRC", "number": "135" },
          { "count": 1, "name": "Repeat Ball", "set": "PRC", "number": "136" },
          { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
          { "count": 2, "name": "Float Stone", "set": "PLF", "number": "99" },
          { "count": 2, "name": "Sky Field", "set": "ROS", "number": "89" },
        ], "energy": [
          { "count": 7, "name": "Metal Energy", "set": "XY", "number": "139" },
          { "count": 3, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Jesper Eriksen',
      flag: '../../assets/flags/denmark.png',
      sprite1: '../../assets/sprites/seismitoad.png',
      sprite2: '../../assets/sprites/crobat.png',
      list: '../../assets/list-icon.png',
      type: 'water',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
          { "count": 2, "name": "Manectric-EX", "set": "PHF", "number": "23" },
          { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
          { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
          { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
          { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
        ], "trainer": [
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "Xerosic", "set": "PHF", "number": "110" },
          { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
          { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 4, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
          { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
          { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
          { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
        ], "energy": [
          { "count": 4, "name": "Lightning Energy", "set": "XY", "number": "135" },
          { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Jon Eng',
      flag: '../../assets/flags/usa.png',
      sprite1: '../../assets/sprites/seismitoad.png',
      sprite2: '../../assets/sprites/crobat.png',
      list: '../../assets/list-icon.png',
      type: 'water',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 3, "name": "Seismitoad-EX", "set": "FFI", "number": "20" },
          { "count": 2, "name": "Manectric-EX", "set": "PHF", "number": "23" },
          { "count": 2, "name": "Crobat", "set": "PHF", "number": "33" },
          { "count": 3, "name": "Golbat", "set": "PHF", "number": "32" },
          { "count": 4, "name": "Zubat", "set": "PLS", "number": "53" },
          { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
          { "count": 1, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
          { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
        ], "trainer": [
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 3, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
          { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 4, "name": "Super Scoop Up", "set": "FFI", "number": "100" },
          { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
          { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Head Ringer Team Flare Hyper Gear", "set": "PHF", "number": "97" },
          { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
          { "count": 2, "name": "Silent Lab", "set": "PRC", "number": "140" },
        ], "energy": [
          { "count": 3, "name": "Lightning Energy", "set": "XY", "number": "135" },
          { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        ]
      },
    },
    {
      firstName: 'Josh Fernando',
      flag: '../../assets/flags/canada.png',
      sprite1: '../../assets/sprites/manectric-mega.png',
      sprite2: '../../assets/sprites/terrakion.png',
      list: '../../assets/list-icon.png',
      type: 'lightning',
      event: '2015 World Championships - Seniors',
      decklist: {
        "pokemon": [
          { "count": 3, "name": "M Manectric-EX", "set": "PHF", "number": "24" },
          { "count": 4, "name": "Manectric-EX", "set": "PHF", "number": "23" },
          { "count": 2, "name": "Terrakion", "set": "LTR", "number": "84" },
          { "count": 2, "name": "Leafeon", "set": "PLF", "number": "11" },
          { "count": 2, "name": "Eevee", "set": "PLF", "number": "89" },
          { "count": 2, "name": "Shaymin-EX", "set": "ROS", "number": "77" },
          { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
        ], "trainer": [
          { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
          { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
          { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
          { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
          { "count": 1, "name": "AZ", "set": "PHF", "number": "91" },
          { "count": 1, "name": "Pokémon Center Lady", "set": "FLF", "number": "93" },
          { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
          { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
          { "count": 4, "name": "VS Seeker", "set": "PHF", "number": "109" },
          { "count": 1, "name": "Max Potion", "set": "EPO", "number": "94" },
          { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
          { "count": 4, "name": "Manectric Spirit Link", "set": "PHF", "number": "100" },
          { "count": 2, "name": "Muscle Band", "set": "XY", "number": "121" },
          { "count": 2, "name": "Float Stone", "set": "BKT", "number": "137" },
          { "count": 3, "name": "Rough Seas", "set": "PRC", "number": "137" },
        ], "energy": [
          { "count": 5, "name": "Lightning Energy", "set": "XY", "number": "135" },
          { "count": 5, "name": "Fighting Energy", "set": "XY", "number": "137" },
        ]
      },
    }
  ]