let masters = [
    {
      "firstName": "Karasu",
      flag: '../../../../assets/flags/japan.png',
      "event": "2024 Fukuoka Champions League - Seniors",
      sprite1: '../../../../assets/sprites/koraidon.png',
      sprite2: '../../../../assets/sprites/roaring-moon.png',
      list: '../../../../assets/list-icon.png',
      "decklist": {
        "pokemon": [
          { "count": 4, "name": "Koraidon", "number": "16", "set": "FR" },
          { "count": 4, "name": "Roaring Moon", "number": "17", "set": "FR" },
          { "count": 2, "name": "Flutter Mane", "number": "18", "set": "FR" },
          { "count": 1, "name": "Great Tusk", "number": "13", "set": "FR" },
          { "count": 1, "name": "Slither Wing", "number": "107", "set": "PAR" },
          { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        ], "trainer": [
            { "count": 4, "name": "Professor Sada's Vitality", "number": "170", "set": "PAR" },
            { "count": 4, "name": "explor", "number": "14", "set": "FR" },
            { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
            { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
            { "count": 4, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
            { "count": 4, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
            { "count": 2, "name": "Ultra Ball", "number": "196", "set": "SVI" },
            { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
            { "count": 2, "name": "Counter Catcher", "number": "160", "set": "PAR" },
            { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
            { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
            { "count": 1, "name": "Awakening Drum", "number": "19", "set": "FR" },
            { "count": 4, "name": "Ancient Booster Energy Capsule", "number": "159", "set": "PAR" },
            { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
            { "count": 3, "name": "PokeStop", "number": "68", "set": "PGO" },
        ], "energy": [
            { "count": 6, "name": "Basic Darkness Energy", "number": "7", "set": "SVE" },
            { "count": 3, "name": "Fighting Energy - Basic", "number": "6", "set": "SVE" },
        ]
      }
    },
    {
      "firstName": "Noa",
      flag: '../../../../assets/flags/japan.png',
      "event": "2024 Fukuoka Champions League - Seniors",
      sprite1: '../../../../assets/sprites/comfey.png',
      sprite2: '../../../../assets/sprites/roaring-moon.png',
      list: '../../../../assets/list-icon.png',
      "decklist": {
        "pokemon": [
          { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
          { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
          { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
          { "count": 1, "name": "Ditto", "number": "132", "set": "MEW" },
          { "count": 1, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
          { "count": 1, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
          { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
          { "count": 1, "name": "Iron Bundle", "number": "56", "set": "PAR" },
          { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" }
        ], "trainer": [
          { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 1, "name": "Boss's Orders", "set": "PAL", "number": "172" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 4, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 3, "name": "Switch", "number": "194", "set": "SVI" },
          { "count": 3, "name": "Buddy Poffin", "number": "9", "set": "FR" },
          { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
          { "count": 1, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
          { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
          { "count": 1, "name": "Prime Catcher", "number": "7", "set": "FR" },
          { "count": 2, "name": "emerg board", "number": "12", "set": "FR" },
          { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
      ], "energy": [
          { "count": 3, "name": "Basic Darkness Energy", "number": "7", "set": "SVE" },
          { "count": 3, "name": "Basic Water Energy", "number": "3", "set": "SVE" },
          { "count": 2, "name": "Basic Lightning Energy", "number": "4", "set": "SVE" },
          { "count": 2, "name": "Basic Psychic Energy", "number": "5", "set": "SVE" },
          ]
      }
    },
    {
      "firstName": "Hiro",
      flag: '../../../../assets/flags/japan.png',
      "event": "2024 Fukuoka Champions League - Seniors",
      sprite1: '../../../../assets/sprites/comfey.png',
      sprite2: '../../../../assets/sprites/roaring-moon.png',
      list: '../../../../assets/list-icon.png',
      "decklist": {
        "pokemon": [
            { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
            { "count": 1, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
            { "count": 1, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
            { "count": 1, "name": "Raikou V", "number": "48", "set": "BRS" },
            { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
            { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
            { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
            { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" }
          ], "trainer": [
            { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
            { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
            { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
            { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
            { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
            { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
            { "count": 4, "name": "Super Rod", "number": "188", "set": "PAL" },
            { "count": 3, "name": "Buddy Poffin", "number": "9", "set": "FR" },
            { "count": 3, "name": "Switch", "number": "147", "set": "CES" },
            { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
            { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
            { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
            { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
            { "count": 1, "name": "Prime Catcher", "number": "7", "set": "FR" },
            { "count": 1, "name": "emerg board", "number": "12", "set": "FR" },
            { "count": 1, "name": "Technical Machine: Devolution", "number": "177", "set": "PAR" },
            { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
            { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
            { "count": 1, "name": "PokeStop", "number": "68", "set": "PGO" },
        ], "energy": [
            { "count": 3, "name": "Basic Darkness Energy", "number": "7", "set": "SVE" },
            { "count": 3, "name": "Basic Water Energy", "number": "3", "set": "SVE" },
            { "count": 2, "name": "Basic Lightning Energy", "number": "4", "set": "SVE" },
            { "count": 2, "name": "Basic Psychic Energy", "number": "5", "set": "SVE" },
            ]
      }
    },
    {
      "firstName": "Rinto",
      flag: '../../../../assets/flags/japan.png',
      "event": "2024 Fukuoka Champions League - Seniors",
      sprite1: '../../../../assets/sprites/goodra-hisui.png',
      sprite2: '../../../../assets/sprites/comfey.png',
      list: '../../../../assets/list-icon.png',
      "decklist": {
        "pokemon": [
          { "count": 2, "name": "Hisuian Goodra VSTAR", "number": "136", "set": "LOR" },
          { "count": 2, "name": "Hisuian Goodra V", "number": "135", "set": "LOR" },
          { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
          { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
          { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
          { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
          { "count": 1, "name": "Zamazenta", "number": "97", "set": "CRZ" },
          { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        ], "trainer": [
            { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
            { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
            { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
            { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
            { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
            { "count": 4, "name": "Switch", "number": "147", "set": "CES" },
            { "count": 3, "name": "Buddy Poffin", "number": "9", "set": "FR" },
            { "count": 3, "name": "Super Rod", "number": "188", "set": "PAL" },
            { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
            { "count": 1, "name": "Ultra Ball", "number": "150", "set": "BRS" },
            { "count": 1, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
            { "count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160" },
            { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
            { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
            { "count": 1, "name": "emerg board", "number": "12", "set": "FR" },
            { "count": 1, "name": "HERO CAPE", "number": "15", "set": "FR" },
            { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
        ], "energy": [
            { "count": 3, "name": "Basic Metal Energy", "number": "8", "set": "SVE" },
            { "count": 3, "name": "Basic Water Energy", "number": "3", "set": "SVE" },
            { "count": 2, "name": "Basic Psychic Energy", "number": "5", "set": "SVE" },
            { "count": 2, "name": "Mist Energy - Special", "number": "4", "set": "FR" },
        ]
      }
    },
  ]