let masters = [
    {
        "firstName": "Christian Sky Mendoza",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Gouging Fire ex", "set": "TEF", "number": "38"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 3, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Eri", "set": "TEF", "number": "146"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 3, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 3, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Technical Machine: Devolution", "set": "PAR", "number": "177"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Rhian Famaran",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 1, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmander", "set": "PR-SV", "number": "47"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Eri", "set": "TEF", "number": "146"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 1, "name": "Professor's Research", "set": "PAF", "number": "88"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Earl Yu",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/gardevoir.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Ralts", "set": "ASR", "number": "60"},
                {"count": 4, "name": "Kirlia", "set": "SIT", "number": "68"},
                {"count": 2, "name": "Gardevoir ex", "set": "PAF", "number": "29"},
                {"count": 1, "name": "Gallade", "set": "ASR", "number": "62"},
                {"count": 2, "name": "Drifloon", "set": "SVI", "number": "89"},
                {"count": 2, "name": "Flutter Mane", "set": "TEF", "number": "78"},
                {"count": 1, "name": "Scream Tail", "set": "PAR", "number": "86"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                {"count": 1, "name": "Radiant Greninja", "set": "ASR", "number": "46"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 4, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 3, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Earthen Vessel", "set": "PAR", "number": "163"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 1, "name": "Hisuian Heavy Ball", "set": "ASR", "number": "146"},
                {"count": 2, "name": "Technical Machine: Evolution", "set": "PAR", "number": "178"},
                {"count": 1, "name": "Hero's Cape", "set": "TEF", "number": "152"},
                {"count": 1, "name": "Luxurious Cape", "set": "PAR", "number": "166"},
                {"count": 1, "name": "Bravery Charm", "set": "PAL", "number": "173"},
                {"count": 1, "name": "Town Store", "set": "OBF", "number": "196"},
            ],
            "energy": [
                {"count": 8, "name": "Psychic", "set": "Energy", "number": "5"},
            ]
        }
    },
    {
        "firstName": "Adrian Gerald Acuzar",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/charizard.png',
        // list: '../../../../assets/list-icon.png',
        list: '../../../../assets/sprites/blank.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "ee", "number": "ee", "set": "ee" },
            ],
            "trainer": [
                { "count": 4, "name": "ee", "number": "ee", "set": "ee" },
            ],
            "energy": [
                { "count": 4, "name": "ee", "number": "ee", "set": "ee" },
            ]
        }
    },
    {
        "firstName": "Joshua Doctolero",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 1, "name": "Charmeleon", "set": "OBF", "number": "27"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Gouging Fire ex", "set": "TEF", "number": "38"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 3, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Hisuian Heavy Ball", "set": "ASR", "number": "146"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Technical Machine: Devolution", "set": "PAR", "number": "177"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Jet Energy", "set": "PAL", "number": "190"},
            ]
        }
    },
    {
        "firstName": "John Eduard Bacalangco",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 2, "name": "Charmander", "set": "PR-SV", "number": "47"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                {"count": 1, "name": "Jirachi", "set": "PAR", "number": "126"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 3, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
                {"count": 1, "name": "Temple of Sinnoh", "set": "ASR", "number": "155"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Aira Pineda",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 2, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor's Research", "set": "PAF", "number": "88"},
                {"count": 1, "name": "Eri", "set": "TEF", "number": "146"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 3, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Technical Machine: Devolution", "set": "PAR", "number": "177"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Kelvin Klein Lazam",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 1, "name": "Charmeleon", "set": "OBF", "number": "27"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Gouging Fire ex", "set": "TEF", "number": "38"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Technical Machine: Devolution", "set": "PAR", "number": "177"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 7, "name": "Fire", "set": "Energy", "number": "2"},
            ]
        }
    },
    {
        "firstName": "Carlo Neria",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Gouging Fire ex", "set": "TEF", "number": "38"},
                {"count": 1, "name": "Chi-Yu ex", "set": "PAL", "number": "40"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 3, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Aki Gulmatico",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/bibarel.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 1, "name": "Charmander", "set": "PGO", "number": "8"},
                {"count": 2, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 3, "name": "Bidoof", "set": "CRZ", "number": "111"},
                {"count": 3, "name": "Bibarel", "set": "BRS", "number": "121"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                {"count": 1, "name": "Jirachi", "set": "PAR", "number": "126"},
                {"count": 1, "name": "Skwovet", "set": "SVI", "number": "151"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 4, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 2, "name": "Ciphermaniac's Codebreaking", "set": "TEF", "number": "145"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 3, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Hisuian Heavy Ball", "set": "ASR", "number": "146"},
                {"count": 2, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Technical Machine: Evolution", "set": "PAR", "number": "178"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 7, "name": "Fire", "set": "Energy", "number": "2"},
            ]
        }
    },
    {
        "firstName": "Norlan de Vera",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/arceus.png',
        sprite2: '../../../../assets/sprites/giratina-origin.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Arceus V", "set": "BRS", "number": "122"},
                {"count": 3, "name": "Arceus VSTAR", "set": "BRS", "number": "123"},
                {"count": 2, "name": "Giratina V", "set": "LOR", "number": "130"},
                {"count": 2, "name": "Giratina VSTAR", "set": "LOR", "number": "131"},
                {"count": 3, "name": "Bidoof", "set": "CRZ", "number": "111"},
                {"count": 2, "name": "Bibarel", "set": "BRS", "number": "121"},
                {"count": 1, "name": "Skwovet", "set": "SVI", "number": "151"},
                {"count": 1, "name": "Iron Leaves ex", "set": "TEF", "number": "25"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Radiant Gardevoir", "set": "LOR", "number": "69"},
                        ],
            "trainer": [
                {"count": 3, "name": "Judge", "set": "SVI", "number": "176"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 2, "name": "Ciphermaniac's Codebreaking", "set": "TEF", "number": "145"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 2, "name": "Capturing Aroma", "set": "SIT", "number": "153"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
            ],
            "energy": [
                {"count": 5, "name": "Grass", "set": "Energy", "number": "1"},
                {"count": 4, "name": "Psychic", "set": "Energy", "number": "5"},
                {"count": 4, "name": "Double Turbo Energy", "set": "BRS", "number": "151"},
                {"count": 1, "name": "Jet Energy", "set": "PAL", "number": "190"},
            ]
        }
    },
    {
        "firstName": "Akira Vargas",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 2, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 2, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Pidgey", "set": "MEW", "number": "16"},
                {"count": 2, "name": "Pidgeot ex", "set": "OBF", "number": "164"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Rotom V", "set": "CRZ", "number": "45"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                        ],
            "trainer": [
                {"count": 3, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 2, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Eri", "set": "TEF", "number": "146"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 2, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Pal Pad", "set": "SVI", "number": "182"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 6, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 2, "name": "Mist Energy", "set": "TEF", "number": "161"},
            ]
        }
    },
    {
        "firstName": "Shawn Matthew Gueco",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard-shiny.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Comfey", "set": "LOR", "number": "79"},
                {"count": 2, "name": "Cramorant", "set": "LOR", "number": "50"},
                {"count": 1, "name": "Sableye", "set": "LOR", "number": "70"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Iron Hands ex", "set": "PAR", "number": "70"},
                {"count": 1, "name": "Mew ex", "set": "MEW", "number": "151"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                {"count": 1, "name": "Iron Bundle", "set": "PAR", "number": "56"},
                {"count": 1, "name": "Spiritomb", "set": "PAL", "number": "89"},
                        ],
            "trainer": [
                {"count": 4, "name": "Colress's Experiment", "set": "LOR", "number": "155"},
                {"count": 2, "name": "Roxanne", "set": "ASR", "number": "150"},
                {"count": 1, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 4, "name": "Mirage Gate", "set": "LOR", "number": "163"},
                {"count": 4, "name": "Switch Cart", "set": "ASR", "number": "154"},
                {"count": 4, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 3, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 3, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 2, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 2, "name": "Pokégear 3.0", "set": "SVI", "number": "186"},
                {"count": 2, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Hisuian Heavy Ball", "set": "ASR", "number": "146"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Rescue Board", "set": "TEF", "number": "159"},
                {"count": 1, "name": "Technical Machine: Devolution", "set": "PAR", "number": "177"},
                {"count": 2, "name": "Artazon", "set": "PAF", "number": "76"},
            ],
            "energy": [
                {"count": 3, "name": "Lightning", "set": "Energy", "number": "4"},
                {"count": 2, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 2, "name": "Psychic", "set": "Energy", "number": "5"},
                {"count": 2, "name": "Jet Energy", "set": "PAL", "number": "190"},
            ]
        }
    },
    {
        "firstName": "Daniel Bernas",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/bibarel.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 3, "name": "Charmander", "set": "OBF", "number": "26"},
                {"count": 1, "name": "Charmander", "set": "PAF", "number": "7"},
                {"count": 1, "name": "Charmeleon", "set": "MEW", "number": "5"},
                {"count": 1, "name": "Charmeleon", "set": "PAF", "number": "8"},
                {"count": 3, "name": "Charizard ex", "set": "PAF", "number": "54"},
                {"count": 2, "name": "Bidoof", "set": "CRZ", "number": "111"},
                {"count": 2, "name": "Bibarel", "set": "BRS", "number": "121"},
                {"count": 1, "name": "Radiant Charizard", "set": "CRZ", "number": "20"},
                {"count": 1, "name": "Entei V", "set": "BRS", "number": "22"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Manaphy", "set": "BRS", "number": "41"},
                {"count": 1, "name": "Jirachi", "set": "PAR", "number": "126"},
                        ],
            "trainer": [
                {"count": 4, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 4, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Rare Candy", "set": "PAF", "number": "89"},
                {"count": 2, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Lost Vacuum", "set": "CRZ", "number": "135"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
                {"count": 1, "name": "Technical Machine: Evolution", "set": "PAR", "number": "178"},
                {"count": 1, "name": "Forest Seal Stone", "set": "SIT", "number": "156"},
                {"count": 1, "name": "Maximum Belt", "set": "TEF", "number": "154"},
                {"count": 1, "name": "Choice Belt", "set": "PAL", "number": "176"},
                {"count": 1, "name": "Town Store", "set": "OBF", "number": "196"},
                {"count": 1, "name": "Collapsed Stadium", "set": "BRS", "number": "137"},
            ],
            "energy": [
                {"count": 7, "name": "Fire", "set": "Energy", "number": "2"},
                {"count": 1, "name": "Jet Energy", "set": "PAL", "number": "190"},
            ]
        }
    },
    {
        "firstName": "Varrian Co Ilao",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/dialga-origin.png',
        sprite2: '../../../../assets/sprites/metang.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 4, "name": "Beldum", "set": "TEF", "number": "113"},
                {"count": 3, "name": "Metang", "set": "TEF", "number": "114"},
                {"count": 2, "name": "Origin Forme Dialga V", "set": "ASR", "number": "113"},
                {"count": 2, "name": "Origin Forme Dialga VSTAR", "set": "ASR", "number": "114"},
                {"count": 1, "name": "Zamazenta", "set": "CRZ", "number": "97"},
                {"count": 1, "name": "Hisuian Basculin", "set": "ASR", "number": "43"},
                {"count": 1, "name": "Hisuian Basculegion", "set": "LOR", "number": "45"},
                {"count": 1, "name": "Radiant Greninja", "set": "ASR", "number": "46"},
                {"count": 1, "name": "Mew ex", "set": "MEW", "number": "151"},
                        ],
            "trainer": [
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 2, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor's Research", "set": "PAF", "number": "88"},
                {"count": 1, "name": "Ciphermaniac's Codebreaking", "set": "TEF", "number": "145"},
                {"count": 1, "name": "Jacq", "set": "SVI", "number": "175"},
                {"count": 1, "name": "Eri", "set": "TEF", "number": "146"},
                {"count": 1, "name": "Professor Turo's Scenario", "set": "PAR", "number": "171"},
                {"count": 3, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 3, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 2, "name": "Great Ball", "set": "PAL", "number": "183"},
                {"count": 1, "name": "Hisuian Heavy Ball", "set": "ASR", "number": "146"},
                {"count": 1, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Switch", "set": "SVI", "number": "194"},
            ],
            "energy": [
                {"count": 17, "name": "Metal", "set": "Energy", "number": "8"},
            ]
        }
    },
    {
        "firstName": "Joshua Myles Lim",
        flag: '../../../../assets/flags/philippines.png',
        "event": "2024 Philippines Regional League #3",
        sprite1: '../../../../assets/sprites/dialga-origin.png',
        sprite2: '../../../../assets/sprites/metang.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                {"count": 2, "name": "Beldum", "set": "TEF", "number": "113"},
                {"count": 2, "name": "Beldum", "set": "SIT", "number": "117"},
                {"count": 3, "name": "Metang", "set": "TEF", "number": "114"},
                {"count": 3, "name": "Origin Forme Dialga V", "set": "ASR", "number": "113"},
                {"count": 2, "name": "Origin Forme Dialga VSTAR", "set": "ASR", "number": "114"},
                {"count": 1, "name": "Zamazenta", "set": "CRZ", "number": "97"},
                {"count": 1, "name": "Mew ex", "set": "MEW", "number": "151"},
                {"count": 1, "name": "Lumineon V", "set": "BRS", "number": "40"},
                {"count": 1, "name": "Radiant Greninja", "set": "ASR", "number": "46"},
                        ],
            "trainer": [
                {"count": 3, "name": "Iono", "set": "PAF", "number": "80"},
                {"count": 3, "name": "Arven", "set": "OBF", "number": "186"},
                {"count": 2, "name": "Boss's Orders", "set": "PAL", "number": "172"},
                {"count": 1, "name": "Professor's Research", "set": "PAF", "number": "88"},
                {"count": 4, "name": "Super Rod", "set": "PAL", "number": "188"},
                {"count": 4, "name": "Ultra Ball", "set": "PAF", "number": "91"},
                {"count": 3, "name": "Nest Ball", "set": "PAF", "number": "84"},
                {"count": 2, "name": "Buddy-Buddy Poffin", "set": "TEF", "number": "144"},
                {"count": 1, "name": "Prime Catcher", "set": "TEF", "number": "157"},
                {"count": 1, "name": "Counter Catcher", "set": "PAR", "number": "160"},
                {"count": 1, "name": "Technical Machine: Evolution", "set": "PAR", "number": "178"},
                {"count": 1, "name": "Defiance Band", "set": "SVI", "number": "169"},
                {"count": 1, "name": "Vitality Band", "set": "SVI", "number": "197"},
            ],
            "energy": [
                {"count": 17, "name": "Metal", "set": "Energy", "number": "8"},
            ]
        }
    },
]