let masters = [
    {
      "firstName": "Apichai Apichainimitdee",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/inteleon-vmax.png",
      sprite2: "../../../../assets/sprites/urshifu-rapid-strike-gmax.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Inteleon VMAX", "number": "79", "set": "FST" },
        { "count": 3, "name": "Inteleon V", "number": "78", "set": "FST" },
        { "count": 2, "name": "Rapid Strike Urshifu VMAX", "number": "88", "set": "BST" },
        { "count": 2, "name": "Rapid Strike Urshifu V", "number": "87", "set": "BST" },
        { "count": 2, "name": "Octillery", "number": "37", "set": "BST" },
        { "count": 2, "name": "Remoraid", "number": "36", "set": "BST" },
        { "count": 1, "name": "Medicham V", "number": "83", "set": "EVS" },
        { "count": 1, "name": "Radiant Alakazam", "number": "59", "set": "SIT" },
        { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
      ], "trainer": [
        { "count": 4, "name": "Professor's Research", "number": "190", "set": "SVI" },
        { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
        { "count": 2, "name": "Melony", "number": "146", "set": "CRE" },
        { "count": 2, "name": "Klara", "number": "145", "set": "CRE" },
        { "count": 2, "name": "Korrina's Focus", "number": "128", "set": "BST" },
        { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
        { "count": 1, "name": "Thorton", "number": "167", "set": "LOR" },
        { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
        { "count": 3, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
        { "count": 2, "name": "Energy Retrieval", "number": "171", "set": "SVI" },
        { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
        { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
        { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
        { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
        { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
        { "count": 3, "name": "Tower of Waters", "number": "138", "set": "BST" },
    ], "energy": [
        { "count": 7, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
        { "count": 4, "name": "Rapid Strike Energy - Special", "number": "140", "set": "BST" },
      ]}
    },
    {
      "firstName": "Tanakon Chumram",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/giratina-origin.png",
      sprite2: "../../../../assets/sprites/comfey.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
        { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        { "count": 1, "name": "Spiritomb", "number": "89", "set": "PAL" }, 
      ],
        "trainer": [
         { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 1, "name": "Thorton", "number": "167", "set": "LOR" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 2, "name": "Switch", "number": "194", "set": "SVI" },
          { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 1, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
          { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
        ], 
          "energy": [
            { "count": 4, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
           { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
           { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
       ]}
    },
    {
      "firstName": "Ingkarith Chinawonges",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/mew-vmax.png",
      sprite2: "../../../../assets/sprites/genesect.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Mew VMAX", "number": "114", "set": "FST" },
        { "count": 4, "name": "Mew V", "number": "113", "set": "FST" },
        { "count": 4, "name": "Genesect V", "number": "185", "set": "FST" },
        { "count": 1, "name": "Meloetta", "number": "124", "set": "FST" },
        { "count": 1, "name": "Eiscue", "number": "44", "set": "BRS" }, 
      ], 
        "trainer": [
          { "count": 2, "name": "Elesa's Sparkle", "number": "233", "set": "FST" },
          { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
          { "count": 1, "name": "Judge", "number": "176", "set": "SVI" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
          { "count": 4, "name": "Cram-o-matic", "number": "229", "set": "FST" },
          { "count": 4, "name": "Power Tablet", "number": "236", "set": "FST" },
          { "count": 3, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
          { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
          { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
          { "count": 1, "name": "Choice Belt", "number": "176", "set": "PAL" },
          { "count": 3, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
          { "count": 2, "name": "Path to the Peak", "number": "148", "set": "CRE" },
          { "count": 2, "name": "Crystal Cave", "number": "144", "set": "EVS" }, 
        ], 
          "energy": [
            { "count": 4, "name": "Fusion Strike Energy - Special", "number": "244", "set": "FST" },
           { "count": 3, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" }
       ]}
    },
    {
      "firstName": "Grist Apichol",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/sableye.png",
      sprite2: "../../../../assets/sprites/comfey.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Dragonite V", "number": "154", "set": "PR-SW" },
        { "count": 1, "name": "Raikou V", "number": "48", "set": "BRS" },
        { "count": 1, "name": "Shaymin V", "number": "13", "set": "BRS" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
    ], "trainer": [
        { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
        { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
        { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
        { "count": 1, "name": "Klara", "number": "145", "set": "CRE" },
        { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
        { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
        { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
        { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
        { "count": 3, "name": "Escape Rope", "number": "125", "set": "BST" },
        { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
        { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
        { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
        { "count": 1, "name": "Canceling Cologne", "number": "136", "set": "ASR" }, 
        { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
        { "count": 1, "name": "Bravery Charm", "number": "173", "set": "PAL" },
        { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
      ], "energy": [
        { "count": 4, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
        { "count": 3, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
        { "count": 2, "name": "Lightning Energy - Basic", "number": "155", "set": "CRZ" },
        { "count": 1, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
        ]}
    },
    {
      "firstName": "Wichakorn Lohavichitranon",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/charizard.png",
      sprite2: "../../../../assets/sprites/pidgeot.png",
     list: '../../../../assets/list-icon.png',
     "decklist": { 
     "pokemon": [
      { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
      { "count": 1, "name": "Charmeleon", "number": "5", "set": "MEW" },
     { "count": 3, "name": "Charmander", "number": "4", "set": "MEW" },
     { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
     { "count": 2, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
      { "count": 2, "name": "Pidgey", "number": "16", "set": "MEW" },
      { "count": 1, "name": "Entei V", "number": "22", "set": "BRS" },
      { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
      { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
      { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
      { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
   ], 
      "trainer": [
       { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
       { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
        { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
        { "count": 1, "name": "Professor's Research", "number": "189", "set": "SVI" },
        { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
        { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
        { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
        { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
        { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
        { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
        { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
        { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
        { "count": 1, "name": "Vitality Band", "number": "197", "set": "SVI" },
        { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
        { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },

       ], 
        "energy": [
         { "count": 8, "name": "Fire Energy - Basic", "number": "153", "set": "CRZ" }
]}
    },
    {
      "firstName": "Manussorn Thongdoung",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/lugia.png",
      sprite2: "../../../../assets/sprites/archeops.png",
     list: '../../../../assets/list-icon.png',
     "decklist": { 
     "pokemon": [
      { "count": 3, "name": "Lugia VSTAR", "number": "139", "set": "SIT" },
      { "count": 4, "name": "Lugia V", "number": "138", "set": "SIT" },
       { "count": 4, "name": "Archeops", "number": "147", "set": "SIT" },
       { "count": 2, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
       { "count": 2, "name": "Snorlax", "number": "143", "set": "LOR" },
       { "count": 1, "name": "Wyrdeer V", "number": "134", "set": "ASR" },
       { "count": 1, "name": "Drapion V", "number": "118", "set": "LOR" },
       { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
       { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
       { "count": 1, "name": "Luxray", "number": "71", "set": "PAL" },
     ], 
       "trainer": [
        { "count": 4, "name": "Boss's Orders", "number": "172", "set": "PAL" },
        { "count": 3, "name": "Professor's Research", "number": "189", "set": "SVI" },
        { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
        { "count": 1, "name": "Professor Burnet", "number": "167", "set": "PR-SW" },
        { "count": 4, "name": "Capturing Aroma", "number": "153", "set": "SIT" },
        { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
         { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
         { "count": 3, "name": "Mesagoza", "number": "178", "set": "SVI" },
         { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" }
       ], 
         "energy": [
          { "count": 4, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" },
          { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
          { "count": 2, "name": "Gift Energy - Special", "number": "171", "set": "LOR" },
           { "count": 2, "name": "Therapeutic Energy - Special", "number": "193", "set": "PAL" },
           { "count": 2, "name": "V Guard Energy - Special", "number": "169", "set": "SIT" },
           { "count": 1, "name": "Luminous Energy - Special", "number": "191", "set": "PAL" },
           { "count": 1, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
]}
    },
    {
      "firstName": "Guntitat Horthong",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/blank.png",
      sprite2: "../../../../assets/sprites/gholdengo.png",
     list: '../../../../assets/list-icon.png',
     "decklist": { 
     "pokemon": [
       { "count": 3, "name": "Gholdengo ex", "number": "139", "set": "PAR" },
       { "count": 3, "name": "Gimmighoul", "number": "87", "set": "PAR" },
       { "count": 1, "name": "Gimmighoul", "number": "88", "set": "PAR" },
       { "count": 2, "name": "Scizor", "number": "141", "set": "OBF" },
       { "count": 3, "name": "Scyther", "number": "123", "set": "MEW" },
       { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
       { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
       { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
       { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
    ], "trainer": [
      { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
      { "count": 3, "name": "Worker", "number": "167", "set": "SIT" },
      { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
      { "count": 1, "name": "Klara", "number": "145", "set": "CRE" },
      { "count": 1, "name": "Cynthia's Ambition", "number": "138", "set": "BRS" },
       { "count": 1, "name": "Lady", "number": "159", "set": "LOR" },
       { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
       { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
       { "count": 4, "name": "Superior Energy Retrieval", "number": "189", "set": "PAL" },
       { "count": 2, "name": "Letter of Encouragement", "number": "189", "set": "OBF" },
       { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
       { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
       { "count": 1, "name": "Energy Retrieval", "number": "171", "set": "SVI" },
       { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
       { "count": 1, "name": "Temple of Sinnoh", "number": "155", "set": "ASR" },
     ], "energy": [
      { "count": 11, "name": "Metal Energy - Basic", "number": "159", "set": "CRZ" },
    ]}
    },
    {
      "firstName": "Yotee Jearanikoon",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/giratina-origin.png",
      sprite2: "../../../../assets/sprites/comfey.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
        { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        { "count": 1, "name": "Spiritomb", "number": "89", "set": "PAL" }, 
      ],
        "trainer": [
         { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
          { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
        ], 
          "energy": [
           { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
            { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
           { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
      ]}
    },
    {
        "firstName": "Krittamet Santivivattanapong",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Thailand Regional League #1",
        sprite1: "../../../../assets/sprites/inteleon-vmax.png",
        sprite2: "../../../../assets/sprites/urshifu-rapid-strike-gmax.png",
        list: '../../../../assets/list-icon.png',
        "decklist": { 
        "pokemon": [
          { "count": 3, "name": "Inteleon VMAX", "number": "79", "set": "FST" },
          { "count": 3, "name": "Inteleon V", "number": "78", "set": "FST" },
          { "count": 2, "name": "Rapid Strike Urshifu VMAX", "number": "88", "set": "BST" },
          { "count": 2, "name": "Rapid Strike Urshifu V", "number": "87", "set": "BST" },
          { "count": 2, "name": "Octillery", "number": "37", "set": "BST" },
          { "count": 2, "name": "Remoraid", "number": "36", "set": "BST" },
          { "count": 1, "name": "Medicham V", "number": "83", "set": "EVS" },
          { "count": 1, "name": "Radiant Alakazam", "number": "59", "set": "SIT" },
          { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
        ], "trainer": [
          { "count": 4, "name": "Professor's Research", "number": "190", "set": "SVI" },
          { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
          { "count": 2, "name": "Melony", "number": "146", "set": "CRE" },
          { "count": 2, "name": "Klara", "number": "145", "set": "CRE" },
          { "count": 2, "name": "Korrina's Focus", "number": "128", "set": "BST" },
          { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 1, "name": "Thorton", "number": "167", "set": "LOR" },
          { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
          { "count": 3, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 2, "name": "Energy Retrieval", "number": "171", "set": "SVI" },
          { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
          { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
          { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
          { "count": 3, "name": "Tower of Waters", "number": "138", "set": "BST" },
      ], "energy": [
          { "count": 7, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
          { "count": 4, "name": "Rapid Strike Energy - Special", "number": "140", "set": "BST" },
          ]}
      },
      {
        "firstName": "Norawit ",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Thailand Regional League #1",
        sprite1: "../../../../assets/sprites/chien-pao.png",
        sprite2: "../../../../assets/sprites/baxcalibur.png",
        list: '../../../../assets/list-icon.png',
        "decklist": { 
        "pokemon": [
          { "count": 3, "name": "Chien-Pao ex", "number": "61", "set": "PAL" },
          { "count": 2, "name": "Baxcalibur", "number": "60", "set": "PAL" },
          { "count": 3, "name": "Frigibax", "number": "57", "set": "PAL" },
          { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
          { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
          { "count": 1, "name": "Drapion V", "number": "118", "set": "LOR" },
          { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
          { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
      ], "trainer": [
          { "count": 4, "name": "Irida", "number": "147", "set": "ASR" },
          { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Superior Energy Retrieval", "number": "189", "set": "PAL" },
          { "count": 4, "name": "Cross Switcher", "number": "230", "set": "FST" },
          { "count": 3, "name": "Rare Candy", "number": "191", "set": "SVI" },
          { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
          { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 2, "name": "Canceling Cologne", "number": "136", "set": "ASR" },
          { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
          { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 1, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
          { "count": 4, "name": "PokeStop", "number": "68", "set": "PGO" },
      ], "energy": [
          { "count": 9, "name": "Water Energy - Basic", "number": "231", "set": "CRE" }
      ]}
      },
      {
        "firstName": "Jednipat Mayo",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Thailand Regional League #1",
        sprite1: "../../../../assets/sprites/giratina-origin.png",
        sprite2: "../../../../assets/sprites/comfey.png",
        list: '../../../../assets/list-icon.png',
        "decklist": { 
        "pokemon": [
          { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
          { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
          { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
          { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
          { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
          { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
          { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        ],
          "trainer": [
           { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
            { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
            { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
            { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
            { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
            { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
            { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
            { "count": 3, "name": "Switch Cart", "number": "154", "set": "ASR" },
            { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
            { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
            { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
            { "count": 1, "name": "Choice Belt", "number": "176", "set": "PAL" },
            { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
          ], 
            "energy": [
             { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
              { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
             { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
              { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
          ]}
      },
      {
        "firstName": "Kachapark Navanimitkul",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Thailand Regional League #1",
        sprite1: "../../../../assets/sprites/arceus.png",
        sprite2: "../../../../assets/sprites/duraludon-gmax.png",
        list: '../../../../assets/list-icon.png',
        "decklist": { 
        "pokemon": [
          { "count": 3, "name": "Arceus VSTAR", "number": "123", "set": "BRS" },
          { "count": 4, "name": "Arceus V", "number": "122", "set": "BRS" },
          { "count": 2, "name": "Duraludon VMAX", "number": "104", "set": "CRZ" },
          { "count": 2, "name": "Duraludon V", "number": "122", "set": "EVS" },
          { "count": 2, "name": "Umbreon VMAX", "number": "95", "set": "EVS" },
          { "count": 2, "name": "Umbreon V", "number": "94", "set": "EVS" },
        ], 
          "trainer": [
            { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
            { "count": 2, "name": "Professor's Research", "number": "190", "set": "SVI" },
            { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
            { "count": 2, "name": "Avery", "number": "130", "set": "CRE" },
            { "count": 1, "name": "Judge", "number": "176", "set": "SVI" },
            { "count": 1, "name": "Karen's Conviction", "number": "144", "set": "CRE" },
            { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
            { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
            { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
            { "count": 2, "name": "Capturing Aroma", "number": "153", "set": "SIT" },
            { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
            { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
            { "count": 3, "name": "Tower of Darkness", "number": "137", "set": "BST" },
            { "count": 2, "name": "Path to the Peak", "number": "148", "set": "CRE" },
          ], 
            "energy": [
              { "count": 5, "name": "Metal Energy - Basic", "number": "159", "set": "CRZ" },
              { "count": 2, "name": "Fighting Energy - Basic", "number": "233", "set": "CRE" },
              { "count": 2, "name": "Darkness Energy - Basic", "number": "158", "set": "CRZ" },
             { "count": 4, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" },
             { "count": 2, "name": "Single Strike Energy - Special", "number": "141", "set": "BST" }
           ]}
      },
      {
        "firstName": "Tanat Leksomboon",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Thailand Regional League #1",
        sprite1: "../../../../assets/sprites/blank.png",
        sprite2: "../../../../assets/sprites/gardevoir.png",
       list: '../../../../assets/list-icon.png',
       "decklist": { 
       "pokemon": [
        { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
        { "count": 2, "name": "Gardevoir", "number": "61", "set": "CRE" },
        { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
        { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
        { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
        { "count": 1, "name": "Ralts", "number": "67", "set": "SIT" },
        { "count": 1, "name": "Zacian V", "number": "16", "set": "CEL" },
        { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
        { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
    ], "trainer": [
        { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
        { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
        { "count": 2, "name": "Professor's Research", "number": "190", "set": "SVI" },
        { "count": 1, "name": "Worker", "number": "167", "set": "SIT" },
        { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
        { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
        { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
        { "count": 2, "name": "Fog Crystal", "number": "140", "set": "CRE" },
        { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
        { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
        { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
        { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
        { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
        { "count": 1, "name": "Moonlight Hill", "number": "1", "set": "FR" },
    ], "energy": [
        { "count": 10, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
        { "count": 2, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
]}
      },
    {
      "firstName": "Napapol Chanvitan",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/giratina-origin.png",
      sprite2: "../../../../assets/sprites/comfey.png",
    list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
        { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
        { "count": 1, "name": "Spiritomb", "number": "89", "set": "PAL" }, 
      ],
        "trainer": [
         { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
          { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
        ], 
          "energy": [
           { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
           { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
           { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
      ]}
    },
    {
      "firstName": "Jasmine Chanvipas",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/giratina-origin.png",
      sprite2: "../../../../assets/sprites/comfey.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
        { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
      ],
        "trainer": [
         { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 1, "name": "Avery", "number": "130", "set": "CRE" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 3, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 3, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
          { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
        ], 
          "energy": [
           { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
           { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
           { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
      ]}
    },
    {
      "firstName": "Jetnipat Likitsombat",
      flag: '../../../../assets/sprites/blank.png',
      "event": "2024 Thailand Regional League #1",
      sprite1: "../../../../assets/sprites/giratina-origin.png",
      sprite2: "../../../../assets/sprites/comfey.png",
      list: '../../../../assets/list-icon.png',
      "decklist": { 
      "pokemon": [
        { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
        { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" }, 
        { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
        { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
        { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
        { "count": 1, "name": "Snorlax", "number": "143", "set": "LOR" },
        { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
        { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
      ],
        "trainer": [
         { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
          { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
          { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
          { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
          { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
          { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
          { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
          { "count": 3, "name": "Switch Cart", "number": "154", "set": "ASR" },
          { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
          { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
          { "count": 1, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
          { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
        ], 
          "energy": [
           { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
           { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
           { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
      ]}
    },
  ]
  