"masters": [
    {
        "name": "Lorenz Matthew Tech",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "charizard",
        "sprite2": "pidgeot",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 1, "name": "Charmeleon", "number": "5", "set": "MEW" },
                { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 2, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 2, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
                { "count": 2, "name": "Pidgey", "number": "16", "set": "MEW" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Delphox V", "number": "27", "set": "LOR" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Professor's Research", "number": "189", "set": "SVI" },
                { "count": 1, "name": "Professor Turo's Scenario", "number": "171", "set": "PAR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Choice Belt", "number": "176", "set": "PAL" },
                { "count": 1, "name": "Lost City", "number": "161", "set": "LOR" }, 
                { "count": 1, "name": "Magma Basin", "number": "144", "set": "BRS" },
            ], "energy": [
                { "count": 8, "name": "Fire Energy - Basic", "number": "153", "set": "CRZ" },
            ]
        }
    },
    {
        "name": "David Jon Del Rosario",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "comfey",
        "sprite2": "sableye",
"decklist": {
            "pokemon": [
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Dragonite V", "number": "154", "set": "PR-SW" },
                { "count": 1, "name": "Raikou V", "number": "48", "set": "BRS" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 4, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 4, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 3, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" }, 
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
                { "count": 3, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 3, "name": "PokeStop", "number": "68", "set": "PGO" },
            ], "energy": [
                { "count": 4, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 2, "name": "Lightning Energy - Basic", "number": "155", "set": "CRZ" },
                { "count": 2, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
            ]
        }
    },
    {
        "name": "Adrian Velasco",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "gardevoir",
"decklist": {
            "pokemon": [
                { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
                { "count": 2, "name": "Gardevoir", "number": "61", "set": "CRE" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
                { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 1, "name": "Ralts", "number": "84", "set": "SVI" },
                { "count": 1, "name": "Scream Tail", "number": "86", "set": "PAR" },
                { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Professor Turo's Scenario", "number": "171", "set": "PAR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Fog Crystal", "number": "140", "set": "CRE" },
                { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Pal Pad", "number": "172", "set": "SSH" },
                { "count": 1, "name": "Luxurious Cape", "number": "166", "set": "PAR" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 10, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 2, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Christian Sky Mendoza",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "charizard",
        "sprite2": "comfey",
"decklist": {
            "pokemon": [
                { "count": 4, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 4, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 4, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Switch", "number": "194", "set": "SVI" }, 
                { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 3, "name": "Artazon", "number": "171", "set": "PAL" },
            ], "energy": [
                { "count": 7, "name": "Fire Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Adrian Gerald Acuzar",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "charizard",
        "sprite2": "comfey",
"decklist": {
            "pokemon": [
                { "count": 4, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 3, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 1, "name": "Raihan", "number": "140", "set": "CRZ" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Switch", "number": "194", "set": "SVI" }, 
                { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Vitality Band", "number": "197", "set": "SVI" },
                { "count": 3, "name": "Artazon", "number": "171", "set": "PAL" },
            ], "energy": [
                { "count": 7, "name": "Fire Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Charles Esco",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "comfey",
        "sprite2": "sableye",
"decklist": {
            "pokemon": [
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Dragonite V", "number": "154", "set": "PR-SW" },
                { "count": 1, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
                { "count": 1, "name": "Alolan Vulpix VSTAR", "number": "34", "set": "SIT" },
                { "count": 1, "name": "Alolan Vulpix V", "number": "33", "set": "SIT" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Klara", "number": "145", "set": "CRE" }, 
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 4, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Energy Recycler", "number": "124", "set": "BST" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" }, 
                { "count": 1, "name": "Echoing Horn", "number": "136", "set": "CRE" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
            ], "energy": [
                { "count": 5, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 4, "name": "Lightning Energy - Basic", "number": "155", "set": "CRZ" },
                { "count": 2, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 2, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Jonathan Abejar",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "charizard",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 2, "name": "Charmeleon", "number": "27", "set": "OBF" },
                { "count": 1, "name": "Charmeleon", "number": "5", "set": "MEW" },
               { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
               { "count": 2, "name": "Charmander", "number": "26", "set": "OBF" },
               { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
               { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
               { "count": 1, "name": "Toedscruel", "number": "17", "set": "PAR" },
               { "count": 1, "name": "Toedscool", "number": "16", "set": "PAR" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
             ], 
                "trainer": [
                 { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                 { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                  { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                  { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                  { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                  { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                  { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
                  { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                  { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                  { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                  { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                  { "count": 2, "name": "Technical Machine: Evolution", "number": "178", "set": "PAR" },
                  { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                  { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
                  { "count": 2, "name": "Town Store", "number": "196", "set": "OBF" },
                  { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
                ], 
                  "energy": [
                   { "count": 7, "name": "Fire Energy - Basic", "number": "153", "set": "CRZ" },
                   { "count": 1, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
             ]
        }
    },
    {
        "name": "John Eduard Bacalangco",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "gardevoir",
"decklist": {
            "pokemon": [
                { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
                { "count": 2, "name": "Gardevoir", "number": "61", "set": "CRE" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
                { "count": 2, "name": "Ralts", "number": "84", "set": "SVI" },
                { "count": 1, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 1, "name": "Ralts", "number": "67", "set": "SIT" },
                { "count": 1, "name": "Scream Tail", "number": "86", "set": "PAR" },
                { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Worker", "number": "167", "set": "SIT" },
                { "count": 4, "name": "Fog Crystal", "number": "140", "set": "CRE" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Luxurious Cape", "number": "166", "set": "PAR" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 10, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 2, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Joshua Doctolero",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "charizard",
        "sprite2": "pidgeot",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 1, "name": "Charmeleon", "number": "5", "set": "MEW" },
                { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 2, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 2, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
                { "count": 2, "name": "Pidgey", "number": "16", "set": "MEW" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Entei V", "number": "22", "set": "BRS" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
            ], "trainer": [
                { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Professor's Research", "number": "189", "set": "SVI" },
                { "count": 1, "name": "Professor Turo's Scenario", "number": "171", "set": "PAR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
                { "count": 1, "name": "Technical Machine: Devolution", "number": "177", "set": "PAR" },
                { "count": 2, "name": "Lost City", "number": "161", "set": "LOR" }, 
            ], "energy": [
                { "count": 8, "name": "Fire Energy - Basic", "number": "153", "set": "CRZ" },
            ]
        }
    },
    {
        "name": "Arvin Jesus R. De Leon",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "chien-pao",
        "sprite2": "baxcalibur",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Chien-Pao ex", "number": "61", "set": "PAL" },
                { "count": 2, "name": "Baxcalibur", "number": "60", "set": "PAL" },
                { "count": 1, "name": "Arctibax", "number": "59", "set": "PAL" },
                { "count": 2, "name": "Frigibax", "number": "57", "set": "PAL" },
                { "count": 1, "name": "Frigibax", "number": "58", "set": "PAL" },
                { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
                { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
                { "count": 1, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Irida", "number": "147", "set": "ASR" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Cross Switcher", "number": "230", "set": "FST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Superior Energy Retrieval", "number": "189", "set": "PAL" },
                { "count": 3, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
                { "count": 1, "name": "Canceling Cologne", "number": "136", "set": "ASR" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 3, "name": "PokeStop", "number": "68", "set": "PGO" },
            ], "energy": [
                { "count": 8, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 1, "name": "Lightning Energy - Basic", "number": "155", "set": "CRZ" }
            ]
        }
    },
    {
        "name": "Aira Pineda",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "gardevoir",
"decklist": {
            "pokemon": [
                { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
                { "count": 3, "name": "Gardevoir", "number": "61", "set": "CRE" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
                { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 1, "name": "Ralts", "number": "67", "set": "SIT" },
                { "count": 1, "name": "Scream Tail", "number": "86", "set": "PAR" },
                { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Worker", "number": "167", "set": "SIT" },
                { "count": 4, "name": "Fog Crystal", "number": "140", "set": "CRE" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Luxurious Cape", "number": "166", "set": "PAR" },
                { "count": 3, "name": "Artazon", "number": "171", "set": "PAL" },
            ], "energy": [
                { "count": 10, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 2, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Antonio Francisco",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "roaring-moon",
"decklist": {
            "pokemon": [
                { "count": 4, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
                { "count": 1, "name": "Morpeko", "number": "121", "set": "PAR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
            ], "trainer": [
                { "count": 4, "name": "Professor Sada's Vitality", "number": "170", "set": "PAR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Cross Switcher", "number": "230", "set": "FST" },
                { "count": 4, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
                { "count": 4, "name": "Dark Patch", "number": "139", "set": "ASR" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Energy Switch", "number": "173", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 2, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" }, 
                { "count": 1, "name": "Pal Pad", "number": "172", "set": "SSH" },
                { "count": 2, "name": "Ancient Booster Energy Capsule", "number": "159", "set": "PAR" },
                { "count": 4, "name": "PokeStop", "number": "68", "set": "PGO" },
            ], "energy": [
                { "count": 7, "name": "Darkness Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
            ]
        }
    },
    {
        "name": "Kiel Sam Talosig",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "giratina-origin",
        "sprite2": "comfey",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
                { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
            ],
            "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 2, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 4, "name": "Path to the Peak", "number": "148", "set": "CRE" },
            ],
            "energy": [
                { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "name": "Jimbo Santiago",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "miraidon",
        "sprite2": "flaaffy",
"decklist": {
            "pokemon": [
                { "count": 3, "name": "Miraidon ex", "number": "81", "set": "SVI" },
                { "count": 2, "name": "Raikou V", "number": "48", "set": "BRS" },
                { "count": 1, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
                { "count": 1, "name": "Raichu V", "number": "45", "set": "BRS" },
                { "count": 2, "name": "Flaaffy", "number": "55", "set": "EVS" },
                { "count": 2, "name": "Mareep", "number": "66", "set": "SVI" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
                { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 1, "name": "Zapdos", "number": "29", "set": "PGO" }, 
            ], "trainer": [
                { "count": 3, "name": "Professor's Research", "number": "189", "set": "SVI" },
                { "count": 2, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 2, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 1, "name": "Judge", "number": "176", "set": "SVI" },
                { "count": 4, "name": "Electric Generator", "number": "170", "set": "SVI" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 3, "name": "Bravery Charm", "number": "173", "set": "PAL" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Technical Machine: Devolution", "number": "177", "set": "PAR" },
                { "count": 1, "name": "Path to the Peak", "number": "148", "set": "CRE" },
                { "count": 1, "name": "Beach Court", "number": "167", "set": "SVI" }, 
                { "count": 1, "name": "Town Store", "number": "196", "set": "OBF" },
            ], "energy": [
                { "count": 13, "name": "Lightning Energy - Basic", "number": "155", "set": "CRZ" },
                { "count": 1, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" }
            ]
        }
    },
    {
        "name": "Christian Anthony Fernandez",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "comfey",
        "sprite2": "sableye",
         "decklist": {
            "pokemon": [
                { "count": 4, "name": "ee", "number": "ee", "set": "ee" },
            ], "trainer": [
                { "count": 4, "name": "ee", "number": "ee", "set": "ee" },
            ], "energy": [
                { "count": 4, "name": "ee", "number": "ee", "set": "ee" },
            ]
        }
    },
    {
        "name": "Fritz Mateo",
        "flag": "../../../assets/sprites/blank.png",
        "event": "2024 Philippines Regional League #1",
        "sprite1": "blank",
        "sprite2": "gardevoir",
"decklist": {
            "pokemon": [
                { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
                { "count": 2, "name": "Gardevoir", "number": "61", "set": "CRE" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
                { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 1, "name": "Ralts", "number": "67", "set": "SIT" },
                { "count": 1, "name": "Scream Tail", "number": "86", "set": "PAR" },
                { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Professor Turo's Scenario", "number": "171", "set": "PAR" },
                { "count": 1, "name": "Worker", "number": "167", "set": "SIT" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Fog Crystal", "number": "140", "set": "CRE" },
                { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Luxurious Cape", "number": "166", "set": "PAR" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 10, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 2, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
            ]
        }
    },
]