let masters = [
  {
    firstName: 'Brandon Salazar',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/landorus-therian.png',
    sprite2: '../../../assets/sprites/raichu.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 2, "name": "Raichu", "set": "XY", "number": "43" },
        { "count": 2, "name": "Pikachu", "set": "XY", "number": "42" },
        { "count": 3, "name": "Landorus-EX", "set": "BCR", "number": "89" },
        { "count": 2, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
        { "count": 1, "name": "Druddigon", "set": "FLF", "number": "70" },
        { "count": 2, "name": "Garbodor", "set": "LTR", "number": "68" },
        { "count": 2, "name": "Trubbish", "set": "DRX", "number": "53" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "N", "set": "NVI", "number": "92" },
        { "count": 3, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Shauna", "set": "XY", "number": "127" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 3, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 2, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 2, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 2, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 1, "name": "Enhanced Hammer", "set": "DEX", "number": "94" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 7, "name": "Fighting Energy", "set": "XY", "number": "137" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Michael Pramawat',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/pyroar.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Pyroar", "set": "FLF", "number": "20" },
        { "count": 4, "name": "Litleo", "set": "FLF", "number": "18" },
        { "count": 1, "name": "Charizard-EX", "set": "FLF", "number": "12" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "Blacksmith", "set": "FLF", "number": "88" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 4, "name": "Pokémon Catcher", "set": "KSS", "number": "36" },
        { "count": 4, "name": "Roller Skates", "set": "XY", "number": "125" },
        { "count": 3, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 2, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Tropical Beach", "set": "PR-BLW", "number": "50" },
      ], "energy": [
        { "count": 8, "name": "Fire Energy", "set": "XY", "number": "133" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Isaiah Williams',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/yveltal.png',
    sprite2: '../../../assets/sprites/garbodor.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Yveltal-EX", "set": "XY", "number": "79" },
        { "count": 2, "name": "Garbodor", "set": "LTR", "number": "68" },
        { "count": 2, "name": "Trubbish", "set": "LTR", "number": "67" },
        { "count": 1, "name": "Darkrai-EX", "set": "DEX", "number": "63" },
        { "count": 1, "name": "Yveltal", "set": "XY", "number": "78" },
        { "count": 1, "name": "Absol", "set": "PLF", "number": "67" },
        { "count": 1, "name": "Sableye", "set": "DEX", "number": "62" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Dark Patch", "set": "DEX", "number": "93" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 2, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 1, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 8, "name": "Darkness Energy", "set": "XY", "number": "138" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Calvin Nordberg',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/kyurem.png',
    sprite2: '../../../assets/sprites/deoxys.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Kyurem", "set": "PLF", "number": "31" },
        { "count": 4, "name": "Deoxys-EX", "set": "PLF", "number": "53" },
        { "count": 2, "name": "Thundurus-EX", "set": "PLF", "number": "38" },
        { "count": 1, "name": "Genesect-EX", "set": "PLB", "number": "11" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Shauna", "set": "XY", "number": "127" },
        { "count": 1, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 4, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 3, "name": "Team Plasma Ball", "set": "PLF", "number": "105" },
        { "count": 3, "name": "Colress Machine", "set": "PLS", "number": "119" },
        { "count": 2, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 1, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 1, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 2, "name": "Water Energy", "set": "XY", "number": "134" },
        { "count": 1, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Plasma Energy", "set": "PLS", "number": "127" },
        { "count": 4, "name": "Prism Energy", "set": "NXD", "number": "93" },
        { "count": 2, "name": "Blend Energy WaterLightningFightingMetal", "set": "DRX", "number": "118" },
      ]
    },
  },
  {
    firstName: 'Adler Pierce',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/virizion.png',
    sprite2: '../../../assets/sprites/genesect.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Virizion-EX", "set": "PLB", "number": "9" },
        { "count": 3, "name": "Genesect-EX", "set": "PLB", "number": "11" },
        { "count": 1, "name": "Sigilyph", "set": "LTR", "number": "66" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 4, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 2, "name": "Shadow Triad", "set": "PLF", "number": "102" },
        { "count": 1, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "G Booster", "set": "PLB", "number": "92" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Energy Switch", "set": "LTR", "number": "112" },
        { "count": 2, "name": "Tool Scrapper", "set": "DRX", "number": "116" },
        { "count": 2, "name": "Enhanced Hammer", "set": "DEX", "number": "94" },
        { "count": 1, "name": "Team Plasma Ball", "set": "PLF", "number": "105" },
        { "count": 1, "name": "Colress Machine", "set": "PLS", "number": "119" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 1, "name": "Town Map", "set": "BCR", "number": "136" },
        { "count": 1, "name": "Escape Rope", "set": "PLS", "number": "120" },
        { "count": 1, "name": "Super Rod", "set": "NVI", "number": "95" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 3, "name": "Skyarrow Bridge", "set": "NXD", "number": "91" },
      ], "energy": [
        { "count": 9, "name": "Grass Energy", "set": "XY", "number": "132" },
        { "count": 4, "name": "Plasma Energy", "set": "PLS", "number": "127" },
      ]
    },
  },
  {
    firstName: 'Oscar Morales',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/pyroar.png',
    // list: '../../../assets/list-icon.png',
    list: '../../../assets/sprites/blank.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {cardImg:'../../assets/cards/2014-2016',numImg:'../../assets/04.png'},
    ]
  },
  {
    firstName: 'Tristan Macek',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/pyroar.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Pyroar", "set": "FLF", "number": "20" },
        { "count": 4, "name": "Litleo", "set": "FLF", "number": "18" },
        { "count": 1, "name": "Charizard-EX", "set": "FLF", "number": "12" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "Blacksmith", "set": "FLF", "number": "88" },
        { "count": 3, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 4, "name": "Roller Skates", "set": "XY", "number": "125" },
        { "count": 3, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 3, "name": "Pokémon Catcher", "set": "KSS", "number": "36" },
        { "count": 2, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Tropical Beach", "set": "PR-BLW", "number": "50" },
      ], "energy": [
        { "count": 8, "name": "Fire Energy", "set": "XY", "number": "133" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Henry Prior',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/flygon.png',
    sprite2: '../../../assets/sprites/dusknoir.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Flygon", "set": "BCR", "number": "99" },
        { "count": 1, "name": "Vibrava", "set": "BCR", "number": "98" },
        { "count": 4, "name": "Trapinch", "set": "BCR", "number": "83" },
        { "count": 2, "name": "Accelgor", "set": "DEX", "number": "11" },
        { "count": 3, "name": "Shelmet", "set": "PLB", "number": "7" },
        { "count": 2, "name": "Dusknoir", "set": "BCR", "number": "63" },
        { "count": 1, "name": "Dusclops", "set": "FLF", "number": "39" },
        { "count": 2, "name": "Duskull", "set": "BCR", "number": "61" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
      ], "trainer": [
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 4, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "Rare Candy", "set": "DEX", "number": "100" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 2, "name": "Max Potion", "set": "EPO", "number": "94" },
        { "count": 2, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 1, "name": "Sacred Ash", "set": "FLF", "number": "96" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 4, "name": "Tropical Beach", "set": "PR-BLW", "number": "50" },
      ], "energy": [
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Darrell Moreno',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/yveltal.png',
    sprite2: '../../../assets/sprites/garbodor.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Yveltal-EX", "set": "XY", "number": "79" },
        { "count": 2, "name": "Garbodor", "set": "LTR", "number": "68" },
        { "count": 2, "name": "Trubbish", "set": "LTR", "number": "67" },
        { "count": 2, "name": "Absol", "set": "PLF", "number": "67" },
        { "count": 1, "name": "Darkrai-EX", "set": "DEX", "number": "63" },
        { "count": 1, "name": "Yveltal", "set": "XY", "number": "78" },
        { "count": 1, "name": "Druddigon", "set": "FLF", "number": "70" },
        { "count": 1, "name": "Keldeo-EX", "set": "BCR", "number": "49" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Dark Patch", "set": "DEX", "number": "93" },
        { "count": 4, "name": "Hypnotoxic Laser", "set": "PLS", "number": "123" },
        { "count": 2, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
        { "count": 2, "name": "Virbank City Gym", "set": "PLS", "number": "126" },
      ], "energy": [
        { "count": 8, "name": "Darkness Energy", "set": "XY", "number": "138" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Jon Bristow',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/pyroar.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 4, "name": "Pyroar", "set": "FLF", "number": "20" },
        { "count": 4, "name": "Litleo", "set": "FLF", "number": "18" },
        { "count": 1, "name": "Charizard-EX", "set": "FLF", "number": "12" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "Blacksmith", "set": "FLF", "number": "88" },
        { "count": 3, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 2, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 4, "name": "Roller Skates", "set": "XY", "number": "125" },
        { "count": 3, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 3, "name": "Pokémon Catcher", "set": "KSS", "number": "36" },
        { "count": 2, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
        { "count": 2, "name": "Tropical Beach", "set": "PR-BLW", "number": "50" },
      ], "energy": [
        { "count": 8, "name": "Fire Energy", "set": "XY", "number": "133" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Mike Newey',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/lugia.png',
    sprite2: '../../../assets/sprites/deoxys.png',
    // list: '../../../assets/list-icon.png',
    list: '../../../assets/sprites/blank.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {cardImg:'../../assets/cards/2014-2016',numImg:'../../assets/04.png'},
    ]
  },
  {
    firstName: 'Ryan Sabelhaus',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/lugia.png',
    sprite2: '../../../assets/sprites/deoxys.png',
    list: '../../../assets/list-icon.png',
    type: 'normal',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 2, "name": "Lugia-EX", "set": "PLS", "number": "108" },
        { "count": 3, "name": "Thundurus-EX", "set": "PLF", "number": "38" },
        { "count": 4, "name": "Deoxys-EX", "set": "PLF", "number": "53" },
        { "count": 1, "name": "Absol", "set": "PLF", "number": "67" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 3, "name": "Shauna", "set": "XY", "number": "127" },
        { "count": 2, "name": "Colress", "set": "PLS", "number": "118" },
        { "count": 2, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 1, "name": "Shadow Triad", "set": "PLF", "number": "102" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "Colress Machine", "set": "PLS", "number": "119" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 3, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 3, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 2, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 1, "name": "Team Plasma Ball", "set": "PLF", "number": "105" },
        { "count": 1, "name": "Escape Rope", "set": "PLS", "number": "120" },
        { "count": 4, "name": "Muscle Band", "set": "XY", "number": "121" },
      ], "energy": [
        { "count": 1, "name": "Lightning Energy", "set": "XY", "number": "135" },
        { "count": 4, "name": "Plasma Energy", "set": "PLS", "number": "127" },
        { "count": 4, "name": "Prism Energy", "set": "NXD", "number": "93" },
        { "count": 3, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
        { "count": 2, "name": "Rainbow Energy", "set": "XY", "number": "131" },
      ]
    },
  },
  {
    firstName: 'Brad Curcio',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/pyroar.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Pyroar", "set": "FLF", "number": "20" },
        { "count": 4, "name": "Litleo", "set": "FLF", "number": "18" },
        { "count": 2, "name": "Electrode", "set": "PLF", "number": "33" },
        { "count": 2, "name": "Voltorb", "set": "XY", "number": "44" },
        { "count": 1, "name": "Charizard-EX", "set": "FLF", "number": "12" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
        { "count": 1, "name": "Jirachi-EX", "set": "PLB", "number": "60" },
      ], "trainer": [
        { "count": 4, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 4, "name": "Blacksmith", "set": "FLF", "number": "88" },
        { "count": 3, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Computer Search", "set": "BCR", "number": "137" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Bicycle", "set": "PLS", "number": "117" },
        { "count": 4, "name": "Pokémon Catcher", "set": "KSS", "number": "36" },
        { "count": 3, "name": "Fiery Torch", "set": "FLF", "number": "89" },
        { "count": 2, "name": "Switch", "set": "KSS", "number": "38" },
        { "count": 1, "name": "Professor's Letter", "set": "XY", "number": "123" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 3, "name": "Muscle Band", "set": "XY", "number": "121" },
      ], "energy": [
        { "count": 8, "name": "Fire Energy", "set": "XY", "number": "133" },
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Russell LaParre',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/flygon.png',
    sprite2: '../../../assets/sprites/dusknoir.png',
    list: '../../../assets/list-icon.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        { "count": 3, "name": "Flygon", "set": "BCR", "number": "99" },
        { "count": 1, "name": "Vibrava", "set": "BCR", "number": "98" },
        { "count": 4, "name": "Trapinch", "set": "BCR", "number": "83" },
        { "count": 3, "name": "Accelgor", "set": "DEX", "number": "11" },
        { "count": 4, "name": "Shelmet", "set": "PLB", "number": "7" },
        { "count": 2, "name": "Dusknoir", "set": "BCR", "number": "63" },
        { "count": 1, "name": "Dusclops", "set": "FLF", "number": "39" },
        { "count": 3, "name": "Duskull", "set": "BCR", "number": "61" },
        { "count": 1, "name": "Mewtwo-EX", "set": "NXD", "number": "54" },
        { "count": 1, "name": "Mr. Mime", "set": "PLF", "number": "47" },
      ], "trainer": [
        { "count": 4, "name": "N", "set": "PR-BLW", "number": "100" },
        { "count": 3, "name": "Skyla", "set": "BCR", "number": "134" },
        { "count": 2, "name": "Ghetsis", "set": "PLF", "number": "101" },
        { "count": 2, "name": "Professor Sycamore", "set": "XY", "number": "122" },
        { "count": 1, "name": "Lysandre", "set": "FLF", "number": "90" },
        { "count": 1, "name": "Dowsing Machine", "set": "PLS", "number": "128" },
        { "count": 4, "name": "Rare Candy", "set": "DEX", "number": "100" },
        { "count": 4, "name": "Ultra Ball", "set": "FLF", "number": "99" },
        { "count": 4, "name": "Level Ball", "set": "NXD", "number": "89" },
        { "count": 2, "name": "Max Potion", "set": "EPO", "number": "94" },
        { "count": 2, "name": "Enhanced Hammer", "set": "DEX", "number": "94" },
        { "count": 1, "name": "Startling Megaphone", "set": "FLF", "number": "97" },
        { "count": 3, "name": "Float Stone", "set": "PLF", "number": "99" },
      ], "energy": [
        { "count": 4, "name": "Double Colorless Energy", "set": "XY", "number": "130" },
      ]
    },
  },
  {
    firstName: 'Frank Diaz',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/flygon.png',
    sprite2: '../../../assets/sprites/dusknoir.png',
    // list: '../../../assets/list-icon.png',
    list: '../../../assets/sprites/blank.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {cardImg:'../../assets/cards/2014-2016',numImg:'../../assets/04.png'},
    ]
  },
  {
    firstName: 'Christopher Nguyen',
    flag: '../../../assets/flags/usa.png',
    sprite1: '../../../assets/sprites/blank.png',
    sprite2: '../../../assets/sprites/yveltal.png',
    // list: '../../../assets/list-icon.png',
    list: '../../../assets/sprites/blank.png',
    type: 'dark',
    event: '2014 US National Championships',
    decklist: {
      "pokemon": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "trainer": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ], "energy": [
        {"count": 0, "name": "example", "set": "aa", "number": "00"},
      ]
    },
    deck: [
      {cardImg:'../../assets/cards/2014-2016',numImg:'../../assets/04.png'},
    ]
  },
]
