let masters = [
    {
        "firstName": "Terry Hilario",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/giratina-origin.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
                { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ],
            "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 4, "name": "Path to the Peak", "number": "148", "set": "CRE" },
            ],
            "energy": [
                { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Rafli Attar Ricco",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/bibarel.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 2, "name": "Charmeleon", "number": "8", "set": "PAF" },
                { "count": 3, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
                { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Entei V", "number": "22", "set": "BRS" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Skwovet", "number": "151", "set": "SVI" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Technical Machine: Evolution", "number": "178", "set": "PAR" },
                { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 7, "name": "Fire Energy - Basic", "number": "2", "set": "SVE" },
                { "count": 1, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Putu Wiguna",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/giratina-origin.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
                { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Spiritomb", "number": "89", "set": "PAL" },
            ],
            "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 2, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 1, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
            ],
            "energy": [
                { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Said Azmi",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/giratina-origin.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
                { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ],
            "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 3, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 3, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 3, "name": "Path to the Peak", "number": "148", "set": "CRE" },
            ],
            "energy": [
                { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 3, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Darwin Rasubala",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard-shiny.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 2, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Klara", "number": "145", "set": "CRE" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 4, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 4, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 3, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Technical Machine: Crisis Punch", "number": "90", "set": "PAF" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
            ], "energy": [
                { "count": 4, "name": "Basic Dark Energy", "number": "7", "set": "SVE" },
                { "count": 2, "name": "Basic Fire Energy", "number": "2", "set": "SVE" },
                { "count": 2, "name": "Basic Psychic Energy", "number": "5", "set": "SVE" },
            ]
        }
    },
    {
        "firstName": "Amin Muhaimin",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/miraidon.png',
        sprite2: '../../../../assets/sprites/flaaffy.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 2, "name": "Miraidon ex", "number": "81", "set": "SVI" },
                { "count": 2, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 2, "name": "Raichu V", "number": "45", "set": "BRS" },
                { "count": 2, "name": "Iron Hands ex", "number": "70", "set": "PAR" },
                { "count": 2, "name": "Flaaffy", "number": "55", "set": "EVS" },
                { "count": 2, "name": "Mareep", "number": "54", "set": "EVS" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Zapdos", "number": "29", "set": "PGO" },
            ], "trainer": [
                { "count": 3, "name": "Peony", "number": "150", "set": "CRE" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 4, "name": "Electric Generator", "number": "170", "set": "SVI" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 3, "name": "Exp. Share", "number": "174", "set": "SVI" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 2, "name": "Town Store", "number": "196", "set": "OBF" },
                { "count": 1, "name": "Beach Court", "number": "167", "set": "SVI" },
            ], "energy": [
                { "count": 15, "name": "Lightning Energy - Basic", "number": "4", "set": "SVE" },
                { "count": 1, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" }
            ]
        }
    },
    {
        "firstName": "Dede Hamid",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 1, "name": "Charmeleon", "number": "27", "set": "OBF" },
                { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 2, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 2, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
                { "count": 2, "name": "Pidgey", "number": "16", "set": "MEW" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Rotom V", "number": "58", "set": "LOR" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 3, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Professor's Research", "number": "190", "set": "SVI" },
                { "count": 1, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Justified Gloves", "number": "143", "set": "CRE" },
                { "count": 1, "name": "Choice Belt", "number": "176", "set": "PAL" },
                { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 7, "name": "Fire Energy - Basic", "number": "2", "set": "SVE" },
            ]
        }
    },
    {
        "firstName": "Jonas Dionisio",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/pidgeot.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 1, "name": "Charmeleon", "number": "27", "set": "OBF" },
                { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 1, "name": "Charmander", "number": "47", "set": "PR-SV" },
                { "count": 2, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
                { "count": 2, "name": "Pidgey", "number": "16", "set": "MEW" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Rotom V", "number": "58", "set": "LOR" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Professor's Research", "number": "190", "set": "SVI" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Technical Machine: Devolution", "number": "177", "set": "PAR" },
                { "count": 1, "name": "Choice Belt", "number": "176", "set": "PAL" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 6, "name": "Fire Energy - Basic", "number": "2", "set": "SVE" },
            ]
        }
    },
    {
        "firstName": "Albert Wijaya",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/zoroark.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 4, "name": "Zoroark", "number": "103", "set": "EVS" },
                { "count": 4, "name": "Zorua", "number": "102", "set": "EVS" },
                { "count": 1, "name": "Gallade", "number": "62", "set": "ASR" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 2, "name": "Hisuian Basculin", "number": "43", "set": "ASR" },
                { "count": 1, "name": "Scizor", "number": "141", "set": "OBF" },
                { "count": 1, "name": "Kleavor", "number": "85", "set": "ASR" },
                { "count": 1, "name": "Scovillain", "number": "29", "set": "SVI" },
                { "count": 1, "name": "Jolteon", "number": "135", "set": "MEW" },
                { "count": 1, "name": "Flareon", "number": "136", "set": "MEW" },
                { "count": 1, "name": "Mightyena", "number": "96", "set": "ASR" },
                { "count": 1, "name": "Slowbro", "number": "20", "set": "PGO" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Zinnia's Resolve", "number": "164", "set": "EVS" },
                { "count": 1, "name": "Arezu", "number": "153", "set": "LOR" },
                { "count": 1, "name": "Raihan", "number": "140", "set": "CRZ" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Bruno", "number": "121", "set": "BST" },
                { "count": 1, "name": "Miriam", "number": "179", "set": "SVI" },
                { "count": 4, "name": "Ultra Ball", "number": "150", "set": "BRS" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 3, "name": "Artazon", "number": "171", "set": "PAL" },
            ], "energy": [
                { "count": 3, "name": "Metal Energy - Basic", "number": "159", "set": "CRZ" },
                { "count": 4, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
                { "count": 1, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" }
            ]
        }
    },
    {
        "firstName": "Tito Santoso",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/gardevoir.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 2, "name": "Gardevoir ex", "number": "86", "set": "SVI" },
                { "count": 2, "name": "Gardevoir", "number": "61", "set": "CRE" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 1, "name": "Kirlia", "number": "60", "set": "CRE" },
                { "count": 3, "name": "Ralts", "number": "84", "set": "SVI" },
                { "count": 1, "name": "Ralts", "number": "67", "set": "SIT" },
                { "count": 1, "name": "Scream Tail", "number": "86", "set": "PAR" },
                { "count": 1, "name": "Cresselia", "number": "74", "set": "LOR" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 1, "name": "Luxray", "number": "71", "set": "PAL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 4, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 2, "name": "Worker", "number": "167", "set": "SIT" },
                { "count": 1, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 1, "name": "Professor Turo's Scenario", "number": "171", "set": "PAR" },
                { "count": 4, "name": "Fog Crystal", "number": "140", "set": "CRE" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Moonlit Hill", "number": "81", "set": "PAF" },
                { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 9, "name": "Basic Psychic Energy", "number": "5", "set": "SVE" },
                { "count": 3, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Daniel Daniharja",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/bibarel.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 2, "name": "Charmeleon", "number": "8", "set": "PAF" },
                { "count": 3, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
                { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Entei V", "number": "22", "set": "BRS" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Skwovet", "number": "151", "set": "SVI" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
            ], "trainer": [
                { "count": 4, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Technical Machine: Evolution", "number": "178", "set": "PAR" },
                { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
                { "count": 2, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
            ], "energy": [
                { "count": 7, "name": "Fire Energy - Basic", "number": "2", "set": "SVE" },
                { "count": 1, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Cedriec",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/charizard.png',
        sprite2: '../../../../assets/sprites/bibarel.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Charizard ex", "number": "125", "set": "OBF" },
                { "count": 2, "name": "Charmeleon", "number": "8", "set": "PAF" },
                { "count": 2, "name": "Charmander", "number": "4", "set": "MEW" },
                { "count": 1, "name": "Charmander", "number": "26", "set": "OBF" },
                { "count": 1, "name": "Charmander", "number": "47", "set": "PR-SV" },
                { "count": 2, "name": "Bibarel", "number": "121", "set": "BRS" },
                { "count": 2, "name": "Bidoof", "number": "111", "set": "CRZ" },
                { "count": 1, "name": "Pidgeot ex", "number": "164", "set": "OBF" },
                { "count": 1, "name": "Pidgey", "number": "16", "set": "MEW" },        
                { "count": 1, "name": "Radiant Charizard", "number": "20", "set": "CRZ" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
                { "count": 1, "name": "Mew", "number": "11", "set": "CEL" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
            ], "trainer": [
                { "count": 3, "name": "Arven", "number": "186", "set": "OBF" },
                { "count": 3, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 3, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 3, "name": "Rare Candy", "number": "191", "set": "SVI" },
                { "count": 2, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Lost Vacuum", "number": "135", "set": "CRZ" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 1, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Technical Machine: Evolution", "number": "178", "set": "PAR" },
                { "count": 1, "name": "Technical Machine: Devolution", "number": "177", "set": "PAR" },
                { "count": 1, "name": "Defiance Band", "number": "169", "set": "SVI" },
                { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Collapsed Stadium", "number": "137", "set": "BRS" },
                { "count": 1, "name": "Lost City", "number": "161", "set": "LOR" },
            ], "energy": [
                { "count": 8, "name": "Fire Energy - Basic", "number": "2", "set": "SVE" },
                { "count": 1, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Nicholas Justin",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/roaring-moon.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
                { "count": 1, "name": "Darkrai VSTAR", "number": "99", "set": "ASR" },
                { "count": 1, "name": "Darkrai V", "number": "98", "set": "ASR" },
                { "count": 1, "name": "Morpeko", "number": "121", "set": "PAR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
                { "count": 1, "name": "Lumineon V", "number": "250", "set": "PR-SW" },
            ], "trainer": [
                { "count": 4, "name": "Professor Sada's Vitality", "number": "170", "set": "PAR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Dark Patch", "number": "139", "set": "ASR" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Cross Switcher", "number": "230", "set": "FST" },
                { "count": 4, "name": "Crossceiver", "number": "231", "set": "FST" },
                { "count": 4, "name": "Trekking Shoes", "number": "145", "set": "CRZ" },
                { "count": 3, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
                { "count": 2, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 1, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 1, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 4, "name": "PokeStop", "number": "68", "set": "PGO" },
            ], "energy": [
                { "count": 9, "name": "Darkness Energy - Basic", "number": "7", "set": "SVE" },
            ]
        }
    },
    {
        "firstName": "Yudhika Bijaury",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/zoroark.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 4, "name": "Zoroark", "number": "103", "set": "EVS" },
                { "count": 4, "name": "Zorua", "number": "102", "set": "EVS" },
                { "count": 1, "name": "Gallade", "number": "62", "set": "ASR" },
                { "count": 3, "name": "Kirlia", "number": "68", "set": "SIT" },
                { "count": 3, "name": "Ralts", "number": "60", "set": "ASR" },
                { "count": 2, "name": "Kleavor", "number": "85", "set": "ASR" },
                { "count": 1, "name": "Aeordactyl", "number": "142", "set": "MEW" },
                { "count": 1, "name": "Scovillain", "number": "29", "set": "SVI" },
                { "count": 1, "name": "Flapple", "number": "120", "set": "EVS" },
                { "count": 1, "name": "Cetitan", "number": "55", "set": "PAL" },
                { "count": 1, "name": "Mabosstiff", "number": "137", "set": "SVI" },
                { "count": 1, "name": "Riachu", "number": "50", "set": "SIT" },
                { "count": 1, "name": "Slowbro", "number": "20", "set": "PGO" },
                { "count": 1, "name": "Hisuian Basculin", "number": "43", "set": "ASR" },
                { "count": 1, "name": "Jirachi", "number": "126", "set": "PAR" },
                { "count": 1, "name": "Manaphy", "number": "41", "set": "BRS" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
            ], "trainer": [
                { "count": 3, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Arezu", "number": "153", "set": "LOR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Professor's Research", "number": "190", "set": "SVI" },
                { "count": 1, "name": "Serena", "number": "164", "set": "SIT" },
                { "count": 1, "name": "Cynthia's Ambition", "number": "138", "set": "BRS" },
                { "count": 1, "name": "Thorton", "number": "167", "set": "LOR" },
                { "count": 1, "name": "Zisu", "number": "159", "set": "ASR" },
                { "count": 4, "name": "Ultra Ball", "number": "150", "set": "BRS" },
                { "count": 4, "name": "Level Ball", "number": "129", "set": "BST" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Artazon", "number": "171", "set": "PAL" },
                { "count": 1, "name": "Practice Studio", "number": "186", "set": "PAL" },
            ], "energy": [
                { "count": 4, "name": "Reversal Energy - Special", "number": "192", "set": "PAL" },
                { "count": 3, "name": "Double Turbo Energy - Special", "number": "151", "set": "BRS" },
                { "count": 1, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
    {
        "firstName": "Diego Fredispancer",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/roaring-moon.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
                { "count": 2, "name": "Galarian Moltres V", "number": "97", "set": "CRE" },
                { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 1, "name": "Morpeko", "number": "121", "set": "PAR" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
            ], "trainer": [
                { "count": 4, "name": "Professor Sada's Vitality", "number": "170", "set": "PAR" },
                { "count": 1, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Dark Patch", "number": "139", "set": "ASR" },
                { "count": 4, "name": "Energy Switch", "number": "173", "set": "SVI" },
                { "count": 4, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 4, "name": "Cross Switcher", "number": "230", "set": "FST" },
                { "count": 3, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 1, "name": "Hisuian Heavy Ball", "number": "146", "set": "ASR" },
                { "count": 1, "name": "Canceling Cologne", "number": "136", "set": "ASR" },

                { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 1, "name": "Emergency Jelly", "number": "155", "set": "SIT" },
                { "count": 4, "name": "PokeStop", "number": "68", "set": "PGO" },
            ], "energy": [
                { "count": 6, "name": "Darkness Energy - Basic", "number": "7", "set": "SVE" },
                { "count": 3, "name": "Water Energy - Basic", "number": "3", "set": "SVE" },
            ]
        }
    },
    {
        "firstName": "Katalio Kishna",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/giratina-origin.png',
        sprite2: '../../../../assets/sprites/comfey.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 3, "name": "Giratina VSTAR", "number": "131", "set": "LOR" },
                { "count": 3, "name": "Giratina V", "number": "130", "set": "LOR" },
                { "count": 4, "name": "Comfey", "number": "79", "set": "LOR" },
                { "count": 1, "name": "Sableye", "number": "70", "set": "LOR" },
                { "count": 1, "name": "Cramorant", "number": "50", "set": "LOR" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
            ],
            "trainer": [
                { "count": 4, "name": "Colress's Experiment", "number": "155", "set": "LOR" },
                { "count": 2, "name": "Roxanne", "number": "150", "set": "ASR" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Avery", "number": "130", "set": "CRE" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Mirage Gate", "number": "163", "set": "LOR" },
                { "count": 3, "name": "Nest Ball", "number": "181", "set": "SVI" },
                { "count": 2, "name": "Super Rod", "number": "188", "set": "PAL" },
                { "count": 2, "name": "Pokegear 3.0", "number": "186", "set": "SVI" },
                { "count": 2, "name": "Switch", "number": "194", "set": "SVI" },
                { "count": 2, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 1, "name": "Counter Catcher", "number": "160", "set": "PAR" },
                { "count": 4, "name": "Path to the Peak", "number": "148", "set": "CRE" },
            ],
            "energy": [
                { "count": 4, "name": "Psychic Energy - Basic", "number": "232", "set": "CRE" },
                { "count": 3, "name": "Grass Energy - Basic", "number": "152", "set": "CRZ" },
                { "count": 3, "name": "Water Energy - Basic", "number": "231", "set": "CRE" },
                { "count": 4, "name": "Jet Energy - Special", "number": "190", "set": "PAL" },
            ]
        }
    },
]

let seniors = [
    {
        "firstName": "--",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2 - Seniors",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/charizard.png',
        list: '../../../../assets/sprites/blank.png',
       
    },
    {
        "firstName": "--",
        flag: '../../../../assets/sprites/blank.png',
        "event": "2024 Indonesia Regional League #2",
        sprite1: '../../../../assets/sprites/blank.png',
        sprite2: '../../../../assets/sprites/roaring-moon.png',
        list: '../../../../assets/list-icon.png',
        "decklist": {
            "pokemon": [
                { "count": 4, "name": "Roaring Moon ex", "number": "124", "set": "PAR" },
                { "count": 2, "name": "Galarian Moltres V", "number": "97", "set": "CRE" },
                { "count": 1, "name": "Mew ex", "number": "151", "set": "MEW" },
                { "count": 1, "name": "Morpeko", "number": "121", "set": "PAR" },
                { "count": 1, "name": "Squawkabilly ex", "number": "169", "set": "PAL" },
                { "count": 1, "name": "Radiant Greninja", "number": "46", "set": "ASR" },
            ], "trainer": [
                { "count": 3, "name": "Professor's Research", "number": "189", "set": "SVI" },
                { "count": 2, "name": "Professor Sada's Vitality", "number": "170", "set": "PAR" },
                { "count": 2, "name": "Boss's Orders", "number": "172", "set": "PAL" },
                { "count": 1, "name": "Iono", "number": "185", "set": "PAL" },
                { "count": 1, "name": "Judge", "number": "176", "set": "SVI" },
                { "count": 4, "name": "Battle VIP Pass", "number": "225", "set": "FST" },
                { "count": 4, "name": "Dark Patch", "number": "139", "set": "ASR" },
                { "count": 4, "name": "Energy Switch", "number": "173", "set": "SVI" },
                { "count": 3, "name": "Trekking Shoes", "number": "145", "set": "CRZ" },
                { "count": 3, "name": "Ultra Ball", "number": "196", "set": "SVI" },
                { "count": 2, "name": "Earthen Vessel", "number": "163", "set": "PAR" },
                { "count": 1, "name": "Pal Pad", "number": "182", "set": "SVI" },
                { "count": 1, "name": "Switch Cart", "number": "154", "set": "ASR" },
                { "count": 1, "name": "Escape Rope", "number": "125", "set": "BST" },
                { "count": 2, "name": "Forest Seal Stone", "number": "156", "set": "SIT" },
                { "count": 2, "name": "Ancient Booster Energy Capsule", "number": "159", "set": "PAR" },
                { "count": 1, "name": "Emergency Jelly", "number": "155", "set": "SIT" },
                { "count": 3, "name": "PokeStop", "number": "68", "set": "PGO" },
                { "count": 1, "name": "Town Store", "number": "196", "set": "OBF" },
            ], "energy": [
                { "count": 9, "name": "Darkness Energy - Basic", "number": "7", "set": "SVE" },
            ]
        }
    }
]